using RCPsiSquared.Core.Inspection;
using RCPsiSquared.Core.Knowledge;

namespace RCPsiSquared.Core.Symmetry;

/// <summary>Which book the chain is read in. The COUNT's definition and the span theorem are
/// book-free; only the two uniform-chain closed forms and the parity forcing are per-book.</summary>
public enum SeatCutBook
{
    /// <summary>The ZZ term on: the single-excitation matrix carries a diagonal.</summary>
    Heisenberg,

    /// <summary>The ZZ term off: the single-excitation matrix has a ZERO diagonal, which is what
    /// makes the parity forcing of <see cref="SeatCutBlindnessClaim.ParityForcedXy"/> possible.</summary>
    Xy,
}

/// <summary>F157, the blind seat: put the Z-dephasing on ONE seat j of an N-site graph, restrict
/// to the single-excitation sector, and count what the watching cannot touch.
///
/// <code>
///     blind(j)  =  N − dim span{ e_j, H e_j, H² e_j, ... }
///               =  N − #{ eigenspaces of H that e_j meets }
///               =  deg gcd( χ(H), χ(H with row and column j struck) )
///
///     uniform open chain, ZZ on  (Heisenberg):  blind(j) = (gcd(2j+1, N) − 1)/2
///     uniform open chain, ZZ off (XY):          blind(j) = gcd(j+1, N+1) − 1
/// </code>
///
/// <para>The Krylov line is the DEFINITION and the primitive; the gcd line is a theorem by
/// Cramer, with no hypothesis beyond the real symmetry H_SE already has (the (j, j) adjugate entry
/// of xI − H IS the characteristic polynomial of the struck matrix, so χ(H_cut)/χ(H) =
/// [(xI − H)⁻¹]_{jj} = Σ_λ ‖P_λ e_j‖²/(x − λ), and the gcd degree is N minus the number of
/// eigenspaces the seat meets). The two chain laws are the clothing, not the phenomenon: they are
/// that criterion evaluated on the committed node bases.</para>
///
/// <para><b>THE SPAN, which is what this claim adds to the registry entry.</b> The stationary
/// manifold of the watched sector is the commutant of the algebra A generated by H and the seat
/// projector P = e_j e_j^†. Because e_j is cyclic in its own Krylov space K, that algebra is
/// forced: every word containing P annihilates W = K^⊥ and lands inside K, and those words already
/// span all of End(K), so A = End(K) ⊕ ℂ[H|_W] and
///
/// <code>
///     dim ker L_SE(j)  =  1 + dim commutant(H|_W)  =  1 + Σ_λ (m_λ − s_λ)²
/// </code>
///
/// with m_λ the multiplicity of λ in H and s_λ = 1 exactly when the seat sees λ. Since blind(j)
/// is the SUM of those same numbers m_λ − s_λ, the identity dim ker = 1 + blind holds exactly when
/// each of them is 0 or 1, that is, exactly when H restricted to the KRYLOV COMPLEMENT W has a
/// simple spectrum (W is the blind subspace at every seat except one whose own ray is H-invariant,
/// the Breaks-for below; the criterion is about W either way).
/// That is a criterion on H|_W and not on H, which is why simplicity of H is sufficient
/// and not necessary, and why the zero bond is not the discriminator: [1,1,0,1,1] breaks the
/// identity because cutting the chain leaves two copies of the same piece, while the zero-bond
/// [1,0,1] holds although it too is cut and degenerate. See
/// <c>docs/proofs/PROOF_BLIND_SEAT_SPAN_AND_NODE_LEMMA.md</c> Theorem A and Corollary C.</para>
///
/// <para><b>The zero-free chain, either book.</b> The same proof's Lemma J (the Jacobi node lemma:
/// on an unreduced Jacobi matrix no eigenvector has two consecutive zeros, hence none vanishes at
/// an end; the spectrum is simple; and an eigenvector vanishes at seat j exactly when its
/// eigenvalue is shared by the two principal submatrices the seat leaves behind; classical for an
/// unreduced Jacobi matrix, proved in the real symmetric case the sector supplies) makes every
/// multiplicity 1, so the criterion is met and dim ker L_SE(j) = 1 + blind(j). Lemma J is also
/// what makes deg gcd equal the number of SHARED ROOTS, since both blocks' polynomials are then
/// squarefree, and it is spent twice for that reason.</para>
///
/// <para><b>The parity-forced third kind, XY only.</b> A zero-diagonal Jacobi block of odd size is
/// singular (det T_m = −b_{m−1}²·det T_{m−2} with det T₁ = 0), so at an odd seat of an odd chain
/// both leftover blocks share the root 0 and the seat is blind at EVERY zero-free profile, signed
/// and irregular included. That a generic chain has no blind seat is a Heisenberg sentence.</para>
///
/// <para><b>Relationship to the parent.</b> <see cref="F4KernelDimensionByComponentsClaim"/> counts
/// the kernel of the FULL dephased Heisenberg Liouvillian with the watching on every site, where
/// it factorises over connected components. This claim is the opposite corner: ONE seat, and the
/// single-excitation sector only. The two meet at F4's open question, which is which seat carries
/// the γ; this claim closes that question in the popcount-1 sector and leaves it open above,
/// where the Wedderburn blocks are no longer forced (<c>docs/CAUGHT_ERRORS.md</c>, 2026-08-24).</para>
///
/// <para><b>Fences.</b> The IDENTIFICATION of the count with the blind subspace breaks at a seat
/// whose own ray is H-invariant (an isolated seat, or its incident bonds detuned to zero): that ray
/// contributes 1 the Krylov complement does not count. The Krylov ↔ gcd identity and the span
/// theorem hold there anyway, both being statements about the Krylov complement. The two-halves
/// phrasing deg gcd(χ(H_left), χ(H_right)) needs a chain with NO ZERO BOND: it is wrong on all
/// 1682 zero-bond (profile, seat) pairs at N = 3..6 on the Heisenberg book and on most, not all,
/// of the XY ones, because what a zero bond has to force is a degeneracy and only the ZZ term
/// forces it always. A float SVD rank miscounts the kernel at small J (21 against the true 6 at
/// N = 11, J = 10⁻⁵, behind a reported gap of 5.95·10³): the routes here are exact.</para>
///
/// <para><b>The two closed forms are two POINTS of one axis, and the axis is now built.</b> Both
/// forms below are stated at a fixed anisotropy: <see cref="BlindHeisenberg"/> at the isotropic
/// Δ = 1 and <see cref="BlindXy"/> at Δ = 0, where the chain carries
/// <c>H = Σ_b J_b (XX + YY + Δ·ZZ)</c>. On the uniform open chain the whole axis is governed by the
/// single integer <c>N_node = |N − 1 − 2j|</c>. At N_node = 0, the reflection-fixed centre seat of an odd
/// chain, the seat is blind at EVERY Δ and the count is (N−1)/2; that half is a proof, the two
/// principal submatrices being conjugate by the chain reflection and so sharing every root. At
/// N_node ≥ 1 the seat is blind exactly at Δ_k = sin((j+1)kπ/N_node)/sin(jkπ/N_node) for k = 1..N_node−1, a finite set
/// which is EMPTY when N_node divides j; a k with N_node | jk is a pole and contributes no Δ. Both forms
/// below are sections of that set, over <b>k ∈ 1..N_node−1</b>, a range that is not decoration: the
/// count at Δ = 1 is #{k : (2j+1)k ≡ N_node (mod 2·N_node)}, which over a full residue system would come to
/// gcd(2j+1, N_node) = 2·blind + 1 instead of blind, and the count at Δ = 0 is #{k : N_node | (j+1)k}, the
/// pole exclusion N_node ∤ jk being automatic since N_node dividing both would divide their difference k.
/// Both are PROVED for every N, not gated. Count over a FULL residue system mod 2·N_node first:
/// there k ↦ 2·N_node − k is an involution whose only fixed point k = N_node is always a solution,
/// so the rest pair off and half of them land in 1..N_node−1 (the fixed point is OUTSIDE that range,
/// which is why the folding cannot be done inside it), and N_node | (j+1)k ⇔ (N_node/h) | k with h = gcd(j+1, N_node); the gcd identities
/// close because N = 2j+1 ± N_node. The FORCED kind is exactly the N_node = 0 case, which re-encodes the
/// reflection condition 2j = N−1 as an integer rather than replacing it, and the MET kind lives on
/// a finite set of Δ containing the isotropic point. The MECHANISM is not new here: Lemma J (J4)
/// of <c>docs/proofs/PROOF_BLIND_SEAT_SPAN_AND_NODE_LEMMA.md</c> gives blind = deg gcd(χ_L, χ_R)
/// for any unreduced Jacobi matrix, and its §(f) already records that the ZZ term changes only the
/// diagonal, which Lemma J never constrains; what is added is the evaluation as Δ moves, and the
/// class of seats blind at NEITHER committed endpoint (N = 9 seat 2, locus ±√2/2, where both gcd
/// laws read 0). End seats are blind 0 at
/// every Δ. Live witness <c>inspect --root blindlocus</c>
/// (<c>SeatBlindnessDeltaLocusWitness</c>), which reports the locus as an INTEGER polynomial (a
/// Chebyshev resultant over ℤ, so its irrational members are named rather than printed as doubles)
/// and cross-checks it against a GF(p) Krylov rank at every rational point. The derivation uses the
/// two-halves phrasing, so it inherits that fence and is stated for the uniform chain, where no
/// zero bond exists. The witness's Krylov route decides only RATIONAL Δ, and the locus meets ℚ
/// only at 0 and ±1 (measured over N = 4..24, not proved), so that route reaches no irrational
/// member; what carries them is a second POLYNOMIAL route, Res_λ(χ_L, χ_R) formed from the two
/// submatrices with no Chebyshev identity used, which agrees with the first as primitive integer
/// polynomials at every one of the 98 (N, seat) pairs of N = 4..16 where both are defined; the other
/// six of the 104 interior pairs are forced centre seats, where both correctly return nothing.</para>
///
/// <para>Live witness <c>inspect --root blind</c> (<c>SeatCutBlindnessWitness</c>), which
/// recomputes the count as an exact GF(p) Krylov rank at two primes and checks it against the
/// closed forms below. Gate <c>simulations/blind_seat_span_proof.py</c> (9 gates, about 19 s) for
/// the proof file, <c>simulations/seat_cut_blindness.py</c> for the criterion and the sweeps.
/// Anchors: <c>docs/proofs/PROOF_BLIND_SEAT_SPAN_AND_NODE_LEMMA.md</c> +
/// <c>experiments/THE_SEAT_THAT_CUTS.md</c> + <c>experiments/THE_BLIND_SITE.md</c> +
/// <c>docs/ANALYTICAL_FORMULAS.md</c> (F157). Typed sibling in the sober base:
/// <c>compute/MirrorWorld/BlindSeat.cs</c>, which owns the COUNT and deliberately not the gcd
/// phrasing.</para></summary>
public sealed class SeatCutBlindnessClaim : Claim
{
    /// <summary>Parent-edge marker: the kernel-dimension claim this one is the one-seat,
    /// popcount-1 corner of, and whose "which seat carries the γ" question it closes in that
    /// sector.</summary>
    public F4KernelDimensionByComponentsClaim KernelByComponents { get; }

    /// <summary>The three-line integer gcd, restated locally per the house habit: the gcd atoms in
    /// <c>FoldResultantCertificate</c> and <c>OcticGaloisCertificate</c> are private and are
    /// polynomial gcds, not this one.</summary>
    private static int Gcd(int a, int b)
    {
        while (b != 0) { (a, b) = (b, a % b); }
        return a < 0 ? -a : a;
    }

    /// <summary>The largest N the closed forms accept. Not physics and not the count's limit: the
    /// Heisenberg form evaluates 2·seat + 1, which overflows int32 near 2^30 and would then take a
    /// gcd of the wrong number rather than throwing. The live witness guards far lower still.</summary>
    public const int MaxN = 1 << 24;

    private static void Check(int n, int seat)
    {
        if (n < 2)
            throw new ArgumentOutOfRangeException(nameof(n), $"a chain needs at least 2 sites; got N = {n}.");
        if (n > MaxN)
            throw new ArgumentOutOfRangeException(nameof(n),
                $"N = {n} exceeds {MaxN}, above which 2*seat+1 overflows int32 and the gcd would be taken of the " +
                "wrong value; this is an arithmetic guard, not a statement about the physics.");
        if (seat < 0 || seat >= n)
            throw new ArgumentOutOfRangeException(nameof(seat), $"seat must lie in 0..{n - 1}; got {seat}.");
    }

    /// <summary>blind(j) on the UNIFORM open chain with the ZZ term on: (gcd(2j+1, N) − 1)/2.
    /// The halving is real and is what separates the two books.</summary>
    public static int BlindHeisenberg(int n, int seat)
    {
        Check(n, seat);
        return (Gcd(2 * seat + 1, n) - 1) / 2;
    }

    /// <summary>blind(j) on the UNIFORM open chain with the ZZ term off: gcd(j+1, N+1) − 1,
    /// with no halving.</summary>
    public static int BlindXy(int n, int seat)
    {
        Check(n, seat);
        return Gcd(seat + 1, n + 1) - 1;
    }

    /// <summary>blind(j) on the uniform open chain of the named book.</summary>
    public static int Blind(int n, int seat, SeatCutBook book) =>
        book == SeatCutBook.Heisenberg ? BlindHeisenberg(n, seat) : BlindXy(n, seat);

    /// <summary>Whether PARITY alone forces this seat blind on the XY book, at every zero-free
    /// profile: an odd seat of an odd chain, where both leftover blocks have odd size and a
    /// zero-diagonal Jacobi block of odd size is singular. Always false on the Heisenberg book,
    /// where blindness off the uniform chain is a coincidence a mirror can force.</summary>
    public static bool ParityForcedXy(int n, int seat, SeatCutBook book)
    {
        Check(n, seat);
        return book == SeatCutBook.Xy && n % 2 == 1 && seat % 2 == 1;
    }

    /// <summary>dim ker L_SE(j) on a ZERO-FREE uniform open chain: 1 + blind(j), by Corollary B of
    /// the proof file. Off the zero-free chain this is a LOWER BOUND on the kernel rather than the
    /// kernel: it is still exact wherever H happens to be simple on the Krylov complement (the
    /// zero-bond [1,0,1] is such a case, and 20 of the twenty-graph table's zero-bond triples are),
    /// and it falls short by Σ(m−s)² − Σ(m−s) elsewhere. The kernel in general is
    /// 1 + dim commutant(H restricted to the Krylov complement), which needs the matrix and not
    /// just N and the seat, and is what the witness computes.</summary>
    public static int SpanOnZeroFreeUniformChain(int n, int seat, SeatCutBook book) =>
        1 + Blind(n, seat, book);

    public SeatCutBlindnessClaim(F4KernelDimensionByComponentsClaim kernelByComponents)
        : base("F157 the blind seat: with the Z-dephasing on ONE seat j, the single-excitation blind count is " +
               "blind(j) = N - dim Krylov(e_j) = deg gcd(chi(H), chi(H with row and column j struck)), an identity " +
               "with no hypothesis beyond the real symmetry H_SE has (Cramer); on the uniform open chain it closes " +
               "to (gcd(2j+1, N) - 1)/2 with the ZZ term and gcd(j+1, N+1) - 1 without, and on the XY book parity " +
               "alone forces every odd seat of every odd chain blind at every zero-free profile. The stationary " +
               "manifold is the commutant of the algebra generated by H and the seat projector, which one cyclic " +
               "vector forces to End(K) + C[H|_W], so dim ker L_SE(j) = 1 + dim commutant(H|_W) = " +
               "1 + sum_lambda (m_lambda - s_lambda)^2; this equals 1 + blind(j) exactly when H restricted to the " +
               "KRYLOV COMPLEMENT has a simple spectrum, which the Jacobi node lemma supplies on any zero-free chain in " +
               "either book. Sufficient and not necessary on H itself; the zero bond is not the discriminator",
               Tier.Tier1Derived,
               "docs/proofs/PROOF_BLIND_SEAT_SPAN_AND_NODE_LEMMA.md (primary: Theorem A, Corollary C, Lemma J) + " +
               "experiments/THE_SEAT_THAT_CUTS.md (the criterion, the chain laws, the Cramer identity) + " +
               "experiments/THE_BLIND_SITE.md (the count, the derivation, the isolated-seat fence) + " +
               "docs/ANALYTICAL_FORMULAS.md (F157) + " +
               "docs/CAUGHT_ERRORS.md (2026-08-24: the commutant framing at general popcount, whose one-seat " +
               "popcount-1 case Theorem A is)")
    {
        KernelByComponents = kernelByComponents ?? throw new ArgumentNullException(nameof(kernelByComponents));
    }

    public override string DisplayName =>
        "F157: the blind seat (the count is a Krylov complement; the span is a commutant)";

    public override string Summary =>
        "blind(j) = N - dim Krylov(e_j) = deg gcd(chi(H), chi(H struck at j)), exact at any graph and any profile; " +
        "dim ker L_SE(j) = 1 + dim commutant(H|_W), which is 1 + blind(j) exactly when H is simple on the " +
        $"KRYLOV COMPLEMENT W, hence on every zero-free chain in either book ({Tier.Label()})";

    protected override IEnumerable<IInspectable> ExtraChildren
    {
        get
        {
            yield return new InspectableNode("the count, and why it is a rank and not a spectrum",
                summary: "blind(j) = N - dim span{e_j, H e_j, ...}. The definition is a RANK on integer inputs, " +
                         "taken over GF(p) at two primes with no eigensolver and nothing to tolerate; a rank mod p " +
                         "can only drop, so the reported blind dimension can only ever be too large, and the LARGER " +
                         "of the two ranks is kept, which is the tighter of the two available upper bounds. (The " +
                         "committed Python route asserts instead that the two primes AGREE, and raises if they do " +
                         "not; the live witness takes the max. Both are sound, in the same direction.) The gcd form is the same number by Cramer, and needs no chain, no " +
                         "simplicity and no zero-bond fence.");

            yield return new InspectableNode("the span is a commutant (Theorem A)",
                summary: "dim ker L_SE(j) = 1 + dim commutant(H|_W) = 1 + sum_lambda (m_lambda - s_lambda)^2, for " +
                         "any Hermitian single-excitation H, any graph, any profile, degenerate spectra included. " +
                         "The one place the hypothesis 'one seat' is spent is the cyclic-vector step: the same " +
                         "e_j that generates K also supplies the projector, which is what forces a FULL matrix " +
                         "block. Gated over Q on both sides at every seat of twenty graphs in both books, 202 of " +
                         "202, zero bonds, negative couplings, disconnection and an isolated seat included.");

            yield return new InspectableNode("when 1 + blind is the kernel (Corollary C)",
                summary: "Exactly when m_lambda - s_lambda <= 1 for every lambda, i.e. when H restricted to the " +
                         "KRYLOV COMPLEMENT W has a simple spectrum (W is the blind subspace at every seat " +
                         "except one whose own ray is H-invariant; the criterion is about W either way). On the " +
                         "twenty-graph table the identity holds on 129 " +
                         "of 202 (graph, book, seat) triples and fails on 73, the 73 being exactly the triples " +
                         "where dim commutant(H|_W) exceeds dim W. Read off two printed " +
                         "integers: the star at N = 5 watched at the HUB has blind 3 and kernel 10, so one " +
                         "eigenvalue of multiplicity 3; K4 has blind 2 and kernel 5, so multiplicity 2; the " +
                         "zero-bond path [1,1,0,1,1] at seat 1 has blind 4 and kernel 7, so the partition (2,1,1).");

            yield return new InspectableNode("the Jacobi node lemma (Lemma J)",
                summary: "On an unreduced Jacobi matrix (every bond nonzero, either book): no eigenvector has two " +
                         "consecutive zero entries, hence none vanishes at an end; the spectrum is simple; and an " +
                         "eigenvector vanishes at seat j exactly when its eigenvalue is shared by the two " +
                         "principal submatrices the seat leaves behind. Simplicity is spent TWICE, once to make " +
                         "the node count a count of eigenvalues and once to make deg gcd the number of shared " +
                         "roots; at a zero bond both spendings fail together, which is why the two-halves " +
                         "phrasing goes wrong there and the Cramer identity does not.");

            yield return new InspectableNode("the two uniform chain laws, and where they disagree",
                summary: $"N = 7: Heisenberg blinds seat 3 alone (blind = {BlindHeisenberg(7, 3)}), XY blinds 1, 3 " +
                         $"and 5 (blind = {BlindXy(7, 1)}, {BlindXy(7, 3)}, {BlindXy(7, 5)}). N = 12: Heisenberg " +
                         $"blinds seats 1, 4, 7 and 10, XY none (seat 4: {BlindHeisenberg(12, 4)} against " +
                         $"{BlindXy(12, 4)}; seat 5 is blind on NEITHER book, {BlindHeisenberg(12, 5)} against " +
                         $"{BlindXy(12, 5)}, and is the wrong seat to compare them at). " +
                         "At the reflection-fixed centre of an odd chain the two agree at (N-1)/2. Why the " +
                         "Heisenberg law stayed invisible for months: against a reflection-parity reading it " +
                         "coincides at every seat of a PRIME chain, and the committed data lived at N = 5 and " +
                         "N = 11, both prime.");

            yield return new InspectableNode("the parity-forced third kind (XY only)",
                summary: $"An odd seat of an odd chain is blind at every zero-free profile, signed and irregular " +
                         $"included: N = 9, seat 3, parity-forced = {ParityForcedXy(9, 3, SeatCutBook.Xy)}, while " +
                         $"the same seat on the Heisenberg book is not ({ParityForcedXy(9, 3, SeatCutBook.Heisenberg)}). " +
                         "The mechanism is that a zero-diagonal Jacobi block of odd size is singular, so both " +
                         "leftover blocks share the root 0.");

            yield return new InspectableNode("scope, and the fences that do not lift",
                summary: "ONE seat and popcount 1: with several seats the algebra need not contain a full matrix " +
                         "block, and above popcount 1 the Wedderburn blocks are not forced (docs/CAUGHT_ERRORS.md, " +
                         "2026-08-24). The count's identification with the blind subspace breaks at a seat whose " +
                         "ray is H-invariant, where that ray contributes 1 the Krylov complement does not count; " +
                         "the span theorem holds there anyway, being about the Krylov complement. The two-halves " +
                         "gcd phrasing needs a chain with no zero bond. Simplicity REVERSES polarity between the " +
                         "two objects: necessary and not sufficient for the XY criterion, sufficient and not " +
                         "necessary for the span on H itself, and necessary AND sufficient on H|_W.");

            yield return new InspectableNode("live lab (the witness)",
                summary: "SeatCutBlindnessWitness recomputes the count at inspect time as an exact GF(p) Krylov " +
                         "rank at two primes on the integer single-excitation matrix, at every seat, and checks it " +
                         "against the closed form of the chosen book: inspect --root blind. Gates: " +
                         "simulations/blind_seat_span_proof.py (9 gates, the proof file) and " +
                         "simulations/seat_cut_blindness.py (the criterion, the sweeps, the twenty-graph table).");

            yield return new InspectableNode("the anisotropy axis, and the second live lab",
                summary: "The two closed forms above are stated at two POINTS of one axis, the isotropic " +
                         "Delta = 1 and the XY Delta = 0, where the chain carries " +
                         "H = Sum_b J_b (XX + YY + Delta*ZZ). On the UNIFORM open chain the whole axis is " +
                         "governed by one integer, the NODE MODULUS N_node = |N - 1 - 2j|, the difference in " +
                         "size between the two pieces the seat cuts the chain into (NOT the d = gcd(j+1, N+1) " +
                         "of the XY node count, which the committed pages write with a bare d: at N = 9 seat 2 " +
                         "that one is 1 and this one is 4). An end seat is blind 0 at every Delta; at " +
                         "N_node = 0, the reflection-fixed centre seat, the seat is blind at EVERY Delta with " +
                         "count (N-1)/2; otherwise it is blind exactly at " +
                         "Delta_k = sin((j+1)k*pi/N_node)/sin(j*k*pi/N_node) over those k = 1..N_node-1 whose " +
                         "denominator does not vanish, and the two laws above are that set's Delta = 1 and " +
                         "Delta = 0 sections. The class that is new is the seat blind at NEITHER: N = 9 seat 2, " +
                         "where both laws read 0 and the locus is +-sqrt(2)/2. Second live lab: " +
                         "inspect --root blindlocus (SeatBlindnessDeltaLocusWitness).");
        }
    }
}
