"""Work with the data the TrichotomyWitness produces (2026-06-18, exploration).

The witness computes, per (N, topology, Q), a full SurvivorReading but the rendered tree
only shows (pc,pr), Dn, route, frozen, |Im|, <n_XY>. Here we read the EXPORTED cube
(simulations/results/trichotomy_cube/cube.csv) and look at ALL of it, especially the
RIGIDITY column (Petermann phase rigidity, never surfaced) and the survivor-sector MIGRATION.

Three questions:
  Q1  Does rigidity separate the three mechanisms? EP (chain) -> r collapses to 0;
      level crossing (ring) -> r stays bounded > 0; commutant (star) -> r ~ 1 at every Q.
  Q2  How does the frozen-interior survivor sector (pc,pr) migrate with Q (the filling walk)?
  Q3  Does the star darkness <n_XY> saturate exactly on g2 = 4/(N-1)?

DATA: results/trichotomy_cube/cube.csv, produced by driving the SHIPPED witness (no re-derivation):
    TrichotomyWitness.ClassifyUnfreeze(topo, N, Q) -> SurvivorReading(pc,pr,dn,route,imMax,nXy,rate,rigidity)
  over N in 3..7, topo in {chain,ring,star}, Q in logspace(0.5, 60, 40). Generated by a ~30-line throwaway
  xUnit [Fact] (_TrichotomyCubeExport) with a row-by-row writer; recreate that loop if the tap recurs.
"""
import csv
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
CUBE = os.path.join(HERE, "results", "trichotomy_cube", "cube.csv")
THRESH = os.path.join(HERE, "results", "trichotomy_cube", "thresholds.csv")


def load_cube():
    rows = []
    with open(CUBE, newline="") as f:
        for r in csv.DictReader(f):
            rows.append(dict(
                N=int(r["N"]), topo=r["topo"], Q=float(r["Q"]),
                pc=int(r["pc"]), pr=int(r["pr"]), dn=int(r["dn"]),
                route=r["route"], frozen=int(r["frozen"]),
                imMax=float(r["imMax"]), nXy=float(r["nXy"]),
                rate=float(r["rate"]), rigidity=float(r["rigidity"]),
            ))
    return rows


def load_thresh():
    t = {}
    with open(THRESH, newline="") as f:
        for r in csv.DictReader(f):
            t[int(r["N"])] = dict(
                chain_Qstar=float(r["chain_Qstar"]),
                ring_Qh=float(r["ring_Qh"]),
                star_g2=float(r["star_g2"]),
            )
    return t


def by(rows, **kw):
    out = [r for r in rows if all(r[k] == v for k, v in kw.items())]
    return sorted(out, key=lambda r: r["Q"])


def main():
    rows = load_cube()
    thr = load_thresh()
    Ns = sorted({r["N"] for r in rows})
    topos = ["chain", "ring", "star"]

    print("=" * 92)
    print("THRESHOLD LADDER (closed forms the witness reports)")
    print("  N   chain Q*    ring Q_h    star g2=4/(N-1)")
    for n in sorted(thr):
        t = thr[n]
        print(f"  {n}   {t['chain_Qstar']:8.4f}   {t['ring_Qh']:8.4f}    {t['star_g2']:8.4f}")

    # ---------- Q1: rigidity as the mechanism discriminator ----------
    print("\n" + "=" * 92)
    print("Q1  RIGIDITY across the un-freeze (Petermann r in (0,1]; r->0 ONLY at a true EP)")
    print("    For each (N,topo): r at the frozen survivor (just below transition) and the")
    print("    un-frozen survivor (just above). EP collapses r; a level crossing keeps r>0.")
    for n in Ns:
        print(f"\n  N={n}")
        for topo in topos:
            seq = by(rows, N=n, topo=topo)
            if not seq:
                continue
            # find the un-freeze: last frozen row, first oscillating row (dn flip 0->1) if any
            flip = None
            for i in range(1, len(seq)):
                if seq[i - 1]["dn"] == 0 and seq[i]["dn"] == 1:
                    flip = i
                    break
            rmin = min(s["rigidity"] for s in seq)
            rmin_q = min(seq, key=lambda s: s["rigidity"])["Q"]
            if flip is None:
                # never un-freezes (star, N>=5): report rigidity range over all Q
                rmax = max(s["rigidity"] for s in seq)
                print(f"    {topo:5s}  NEVER un-freezes   r in [{rmin:.4f}, {rmax:.4f}]"
                      f"  (min r at Q={rmin_q:.2f})")
            else:
                below, above = seq[flip - 1], seq[flip]
                print(f"    {topo:5s}  un-freeze Q~[{below['Q']:.2f},{above['Q']:.2f}]  "
                      f"r_frozen={below['rigidity']:.4f} -> r_osc={above['rigidity']:.4f}  "
                      f"| global min r={rmin:.4f} @Q={rmin_q:.2f}")

    # ---------- Q2: survivor-sector migration (the filling walk) ----------
    print("\n" + "=" * 92)
    print("Q2  SURVIVOR-SECTOR MIGRATION with Q (frozen interior (p,p) before the un-freeze)")
    print("    Listing the distinct (pc,pr) the survivor visits, low->high Q, with the Q it switches.")
    for n in Ns:
        print(f"\n  N={n}  (half filling = ({n//2},{n//2}))")
        for topo in topos:
            seq = by(rows, N=n, topo=topo)
            if not seq:
                continue
            walk = []
            for s in seq:
                key = (s["pc"], s["pr"])
                if not walk or walk[-1][0] != key:
                    walk.append((key, s["Q"], s["dn"]))
            desc = "  ".join(f"{k}@Q={q:.2f}{'*' if dn else ''}" for k, q, dn in walk)
            print(f"    {topo:5s}: {desc}")

    # ---------- Q3: star darkness saturates on the ceiling ----------
    print("\n" + "=" * 92)
    print("Q3  STAR DARKNESS <n_XY> -> g2 = 4/(N-1)?  (highest-Q row vs the closed form)")
    for n in Ns:
        seq = by(rows, N=n, topo="star")
        if not seq:
            continue
        top = seq[-1]
        g2 = thr.get(n, {}).get("star_g2", float("nan"))
        print(f"    N={n}  <n_XY>(Q={top['Q']:.1f})={top['nXy']:.5f}   g2=4/(N-1)={g2:.5f}   "
              f"diff={top['nXy']-g2:+.2e}")


if __name__ == "__main__":
    main()
