"""Sector-pinned rigidity sweep analysis (2026-06-18).

For each (N, topology, pinned sector) we swept Q finely and recorded the slowest-mode
|Im| and Petermann rigidity. An EXCEPTIONAL POINT shows TWO coincident signatures:
  (i)  rigidity r -> 0 (left/right eigenvectors coalesce), and
  (ii) |Im| onsets from 0 with a square-root edge (two real modes -> complex pair).
A mere LEVEL CROSSING keeps r bounded away from 0 (no eigenvector coalescence).

So pinning the sector and watching r(Q) and |Im|(Q) tells us WHICH mechanism each
topology un-freezes by, in an observable (rigidity) the witness computes but never shows.

DATA: results/trichotomy_cube/rigidity_sweep.csv, produced by driving the SHIPPED witness statics
    TrichotomyWitness.CarbonImAndRigidity(topo, N, Q, pc, pr) -> (|Im|, rigidity)
    TrichotomyWitness.CarbonSlowestRate  (topo, N, Q, pc, pr) -> rate
  over N in 4..6, topo in {chain,ring,star}, sector in {(0,1),(m,m)}, Q in linspace(0.6, 6, 60).
  Generated by a ~25-line throwaway xUnit [Fact] (_TrichotomyRigiditySweep); recreate if the tap recurs.
"""
import csv
import math
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
SWEEP = os.path.join(HERE, "results", "trichotomy_cube", "rigidity_sweep.csv")


def load():
    series = defaultdict(list)  # (N, topo, sector) -> list of (Q, imMax, rig, rate)
    with open(SWEEP, newline="") as f:
        for r in csv.DictReader(f):
            key = (int(r["N"]), r["topo"], r["sector"])
            series[key].append((float(r["Q"]), float(r["imMax"]),
                                float(r["rigidity"]), float(r["rate"])))
    for k in series:
        series[k].sort()
    return series


def im_onset_Q(seq, thr=1e-4):
    """First Q where |Im| rises above thr (the oscillation birth)."""
    for q, im, _, _ in seq:
        if im > thr:
            return q
    return None


def main():
    series = load()
    Ns = sorted({k[0] for k in series})
    topos = ["chain", "ring", "star"]

    print("=" * 100)
    print("SECTOR-PINNED EP PROBE: min rigidity (r->0 = EP) vs |Im| onset (oscillation birth)")
    print("  per (N, topo, sector):  r_min @ Q  |  |Im|-onset Q  |  do they coincide? (EP) ")
    print("=" * 100)
    for n in Ns:
        half = n // 2
        for sector in ["0_1", f"{half}_{half}"]:
            print(f"\n  N={n}  sector ({sector.replace('_',',')})")
            for topo in topos:
                seq = series.get((n, topo, sector))
                if not seq:
                    continue
                rmin_q, rmin = min(((q, r) for q, im, r, rate in seq), key=lambda t: t[1])
                onset = im_onset_Q(seq)
                # rigidity right at the onset (interp to nearest sample)
                r_at_onset = None
                if onset is not None:
                    r_at_onset = min(seq, key=lambda t: abs(t[0] - onset))[2]
                coincide = (onset is not None and abs(rmin_q - onset) < 0.15)
                tag = "  <-- EP (r->0 AT |Im| birth)" if (coincide and rmin < 0.15) else ""
                onset_s = f"{onset:.3f}" if onset is not None else "  none "
                r_at_s = f"{r_at_onset:.4f}" if r_at_onset is not None else "  -  "
                print(f"    {topo:5s}  r_min={rmin:.4f}@Q={rmin_q:.3f}   |Im|-onset@Q={onset_s}"
                      f"   r@onset={r_at_s}{tag}")

    # ---- focused: the (0,1) band-edge rigidity profile around each chain Q* ----
    print("\n" + "=" * 100)
    print("CHAIN (0,1) band-edge rigidity profile near Q* (is there a dip, or is it flat r=1?)")
    for n in Ns:
        seq = series.get((n, "chain", "0_1"))
        if not seq:
            continue
        rmin_q, rmin = min(((q, r) for q, im, r, rate in seq), key=lambda t: t[1])
        rmax = max(r for q, im, r, rate in seq)
        # sample the profile coarsely
        print(f"\n  N={n}: r ranges [{rmin:.4f}, {rmax:.4f}], min @Q={rmin_q:.3f}, onset@Q={im_onset_Q(seq)}")
        marks = [s for i, s in enumerate(seq) if i % 22 == 0]
        for q, im, r, rate in marks:
            bar = "#" * int(round(r * 40))
            print(f"      Q={q:5.2f}  r={r:.4f} |Im|={im:8.2e}  {bar}")

    # ---- the same for ring (0,1): is the band degenerate (r<1 plateau)? ----
    print("\n" + "=" * 100)
    print("RING (0,1) band-edge rigidity profile (degenerate band => r plateau below 1?)")
    for n in Ns:
        seq = series.get((n, "ring", "0_1"))
        if not seq:
            continue
        rmin_q, rmin = min(((q, r) for q, im, r, rate in seq), key=lambda t: t[1])
        rmax = max(r for q, im, r, rate in seq)
        hi = [r for q, im, r, rate in seq if q > 4.0]
        plateau = sum(hi) / len(hi) if hi else float("nan")
        print(f"  N={n}: r in [{rmin:.4f},{rmax:.4f}], min@Q={rmin_q:.3f}, high-Q(>4) mean r={plateau:.4f}")


if __name__ == "__main__":
    main()
