"""The two things F157 owed a proof file, gated from below on exact integers.

F157 registered the blind count as a theorem and marked TWO pieces prose-argued
with no proof file: the Jacobi NODE LEMMA that the two-halves criterion
consumes, and the SPAN identity dim ker L_SE(j) = 1 + blind(j).  This script is
the gate for both, and for the theorem that replaces the second.

WHAT THE SPAN IDENTITY REALLY IS.  The single-excitation kernel is the commutant
of the algebra A generated by H and the seat projector P = e_j e_j^T.  THAT
FRAMING IS THE REPO'S, not this script's, and it is committed in three places on
2026-08-24: docs/CAUGHT_ERRORS.md (the fifty-re-bases entry),
experiments/THE_SEAT_THAT_CUTS.md section 5, which claims it in its own ownership
table, and the F4 seat sub-bullets of docs/ANALYTICAL_FORMULAS.md.  All three
state dim ker = sum m_i^2 over A's Wedderburn blocks (n_i, m_i), and all three
work the same single-excitation sector this script does.  What was NOT written
down is that with ONE seat the blocks are forced and can be named.  Write K for
the seat's Krylov space and W = K^perp, so blind(j) = dim W.
Every word in H and P that contains P annihilates W and lands inside K, and
because e_j is cyclic in K those words already span the whole of End(K).  So

    A = End(K)  (+)  C[H restricted to W]

as an algebra, and its commutant is C.Id_K (+) the commutant of H|_W:

    dim ker L_SE(j)  =  1  +  dim commutant(H|_W)
                     =  1  +  sum_lambda (m_lambda - s_lambda)^2

with m_lambda the multiplicity of lambda in H and s_lambda = 1 if the seat sees
lambda (P_lambda e_j != 0) and 0 if it does not.  Since blind(j) is the SUM of
those same numbers m_lambda - s_lambda, the identity dim ker = 1 + blind holds
exactly when every one of them is 0 or 1, that is, when H restricted to the
KRYLOV COMPLEMENT W has a simple spectrum.  (W is the blind subspace at every
seat but one kind: at a seat whose own ray is H-invariant the blind subspace
carries one dimension W does not, F157's Breaks-for, and the criterion is about
W either way.)  That is the sharp criterion, and it decides every failure the
twenty-graph table records, which the zero-bond reading does not: run_commutant
counts how far that reading misses, in both directions.

THE NODE LEMMA is what carries the zero-free chain into that criterion.  For an
unreduced Jacobi matrix (real symmetric tridiagonal, every off-diagonal nonzero)
no eigenvector has two consecutive zeros, hence none vanishes at an end; the
spectrum is simple; and an eigenvector vanishes at seat j exactly when its
eigenvalue is shared by the two principal submatrices the seat leaves behind.
Simplicity makes every m_lambda = 1, so the criterion is met and the span
identity follows; it also makes both blocks' polynomials squarefree, which is
why the SHARED-ROOT count and the GCD DEGREE agree.

Every number below is exact: integer Hamiltonians, Fraction characteristic
polynomials, Fraction eliminations, and GF(p) ranks on integer inputs.  No
eigensolver, no tolerance, nothing rounded.

WHERE THE ROUTES ARE ONE-SIDED, AND WHERE THEY ARE DELIBERATELY NOT.  A rank
mod p can only drop, so a dimension read as a nullity mod p can only come out
too LARGE.  Both sides of Theorem A are nullities, so computing both mod p at
the same prime would leave them free to inflate together; G6 therefore takes
both over Q, where there is no such freedom, and G6b pins the committed GF(p)
kernel route against the rational one afterwards.  G8, which sweeps thousands
of profiles rather than twenty graphs, keeps the committed GF(p) kernel route
for cost, and there the two sides do come from independent routes (a kernel
rank and a Krylov rank on different matrices).

This script is the gate for docs/proofs/PROOF_BLIND_SEAT_SPAN_AND_NODE_LEMMA.md,
whose Lemma J is G1..G5, Theorem A is G6 and G6b, Corollary C is G7 and
Corollary B is G8.

    python simulations/blind_seat_span_proof.py [lemma|commutant|chain|all]

Companion: simulations/seat_cut_blindness.py, whose primitives this script
imports rather than restates (the integer H, the exact kernel, the Krylov blind
count, the twenty-graph list).
"""

import itertools
import os
import random
import sys
from fractions import Fraction

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import seat_cut_blindness as S


# ----------------------------------------------------------------- primitives

ONE = [Fraction(1)]


def _sub(h, lo, hi):
    """The principal submatrix on sites lo..hi-1.  NOT an induced subgraph."""
    return [row[lo:hi] for row in h[lo:hi]]


def _poly_gcd(f, g):
    """gcd(f, g) over Q as a POLYNOMIAL, ascending coefficients.

    seat_cut_blindness._poly_gcd_degree returns only the degree, and the proof
    needs the polynomial itself to ask whether its roots are roots of chi(H)
    as well.
    """
    def trim(q):
        q = [Fraction(x) for x in q]
        while len(q) > 1 and q[-1] == 0:
            q.pop()
        return q

    f, g = trim(f), trim(g)
    while not (len(g) == 1 and g[0] == 0):
        if len(f) < len(g):
            f, g = g, f
            continue
        shift, factor = len(f) - len(g), f[-1] / g[-1]
        for i, c in enumerate(g):
            f[shift + i] -= factor * c
        f = trim(f)
        if len(f) < len(g) or (len(f) == 1 and f[0] == 0):
            f, g = g, f
    return f


def _is_squarefree(poly):
    """A real symmetric matrix has a simple spectrum iff its chi is squarefree.

    Degree 0 and 1 are squarefree with nothing to compute, and they are reached:
    an end seat leaves one block empty, whose chi is the constant 1.
    """
    if len(poly) <= 2:
        return True
    der = [poly[k] * k for k in range(1, len(poly))]
    return S._poly_gcd_degree(poly, der) == 0


def _rref(rows, ncols):
    """Reduced row echelon form over Q, returning (rows, pivot columns)."""
    m = [[Fraction(x) for x in r] for r in rows]
    pivots, r = [], 0
    for c in range(ncols):
        piv = next((i for i in range(r, len(m)) if m[i][c] != 0), None)
        if piv is None:
            continue
        m[r], m[piv] = m[piv], m[r]
        inv = Fraction(1) / m[r][c]
        m[r] = [x * inv for x in m[r]]
        for i in range(len(m)):
            if i != r and m[i][c] != 0:
                f = m[i][c]
                m[i] = [a - f * b for a, b in zip(m[i], m[r])]
        pivots.append(c)
        r += 1
        if r == len(m):
            break
    return m, pivots


def blind_basis(n, bonds, seat, zz):
    """An exact rational basis of the blind space W = K^perp, and H beside it.

    W is the orthogonal complement of the Krylov space span{e_j, H e_j, ...},
    i.e. the nullspace of the Krylov matrix read as a system.  Computed over Q
    rather than GF(p): the COUNT is already gated at two primes in the
    companion script, and what is needed here is the SUBSPACE.
    """
    h = S.se_hamiltonian_int(n, bonds, zz)
    vec = [1 if s == seat else 0 for s in range(n)]
    rows = [vec[:]]
    for _ in range(n):
        vec = [sum(h[a][b] * vec[b] for b in range(n)) for a in range(n)]
        rows.append(vec[:])
    m, pivots = _rref(rows, n)
    free = [c for c in range(n) if c not in pivots]
    basis = []
    for f in free:
        v = [Fraction(0)] * n
        v[f] = Fraction(1)
        for i, c in enumerate(pivots):
            v[c] = -m[i][f]
        basis.append(v)
    return h, basis


def restrict(h, basis):
    """H restricted to span(basis), in that basis, exactly.

    Asserts H-invariance rather than assuming it: the solve leaves a nonzero
    residual row iff the image escapes the span, and that would be a finding
    about the construction, not something to tolerate.
    """
    w = len(basis)
    if w == 0:
        return []
    n = len(h)
    images = [[sum(Fraction(h[a][b]) * v[b] for b in range(n)) for a in range(n)]
              for v in basis]
    aug = [[basis[k][r] for k in range(w)] + [img[r] for img in images]
           for r in range(n)]
    m, pivots = _rref(aug, w)
    if len(pivots) != w:
        raise AssertionError("the blind basis is not independent")
    for row in m[w:]:
        if any(x != 0 for x in row):
            raise AssertionError("the blind space is not H-invariant")
    return [[m[i][w + k] for k in range(w)] for i in range(w)]


def _rank_q(rows, ncols):
    """Rank over Q.  Exact, and NOT one-sided the way a rank mod p is."""
    _, pivots = _rref(rows, ncols)
    return len(pivots)


def commutant_dim(mat):
    """dim { Y : [mat, Y] = 0 }, exactly, over Q.

    Over the rationals rather than GF(p) on purpose: this is the right side of
    the theorem, and the left side is a nullity too, so two modular ranks at the
    same prime would both be able to come out too large in the same direction.
    The matrices here are (w^2) x (w^2) with w = dim W at most 4 on the swept
    graphs, so exactness costs nothing.
    """
    w = len(mat)
    if w == 0:
        return 0
    rows = []
    for a in range(w):
        for b in range(w):
            row = [Fraction(0)] * (w * w)
            for i in range(w):
                row[i * w + b] += mat[a][i]
                row[a * w + i] -= mat[i][b]
            rows.append(row)
    return w * w - _rank_q(rows, w * w)


def kernel_dim_q(n, bonds, seat, zz):
    """dim ker L_SE(seat), exactly over Q.

    The same operator `seat_cut_blindness.exact_kernel_dim` ranks over GF(p),
    rebuilt here over the rationals so that the theorem's two sides do not
    share a one-sided route.  The allowed-entry restriction is that docstring's:
    ker L = { rho : [H, rho] = 0, and rho_ij = 0 wherever the dephased seat's
    bit differs between i and j }.
    """
    h = S.se_hamiltonian_int(n, bonds, zz)
    allowed = [(i, j) for i in range(n) for j in range(n)
               if (i == seat) == (j == seat)]
    index = {c: k for k, c in enumerate(allowed)}
    rows = []
    for a in range(n):
        for b in range(n):
            row = [Fraction(0)] * len(allowed)
            for (i, j) in allowed:
                v = 0
                if j == b:
                    v += h[a][i]
                if i == a:
                    v -= h[j][b]
                if v:
                    row[index[(i, j)]] = Fraction(v)
            if any(x != 0 for x in row):
                rows.append(row)
    return len(allowed) - _rank_q(rows, len(allowed))


def zero_free_profiles(nmax=8):
    """Zero-free integer bond profiles: uniform, signed, irregular, random.

    A zero bond is excluded by construction, that being the lemma's hypothesis;
    what is NOT excluded is a negative or irregular coupling, which is where an
    argument quietly assuming positivity would break.
    """
    out = []
    for n in range(2, nmax + 1):
        out.append((n, [1] * (n - 1)))
        out.append((n, [2] * (n - 1)))
    for n in range(3, 7):
        for js in itertools.product([1, -1, 2, -3], repeat=n - 1):
            out.append((n, list(js)))
    rnd = random.Random(20260825)
    for _ in range(300):
        n = rnd.randint(3, nmax)
        out.append((n, [rnd.choice([-5, -3, -2, -1, 1, 2, 3, 4, 7])
                        for _ in range(n - 1)]))
    return out


def _bonds(js):
    return [(i, i + 1, js[i]) for i in range(len(js))]


# ------------------------------------------------------------------- the parts

def run_lemma():
    """G1..G5: the Jacobi node lemma, on zero-free profiles, both books."""
    print("LEMMA J, THE JACOBI NODE LEMMA.  H is the integer single-excitation")
    print("matrix of a chain with no zero bond, so it is an unreduced Jacobi")
    print("matrix in either book: real symmetric, tridiagonal, every")
    print("off-diagonal 2J_b nonzero.  L and R are the principal submatrices")
    print("the seat leaves behind, chi a characteristic polynomial.")
    print()
    print("  G1  no eigenvector vanishes at an end, read as blind(0) =")
    print("      blind(N-1) = 0")
    print("  G2  the spectrum is simple: chi(H) is squarefree")
    print("  G3  both blocks are unreduced Jacobi too, so chi(L) and chi(R)")
    print("      are squarefree and deg gcd COUNTS the shared roots")
    print("  G4  every shared root of the two blocks is a root of chi(H)")
    print("      (the gluing direction: a shared root really is a node)")
    print("  G5  deg gcd(chi(L), chi(R)) = blind(j), the node count and the")
    print("      Krylov complement agreeing at every seat")
    print()
    profiles = zero_free_profiles()
    tally = {k: [0, 0] for k in ("G1", "G2", "G3", "G4", "G5")}
    failures = []

    def note(gate, ok, what):
        tally[gate][1 if ok else 0] += 1
        if not ok:
            failures.append((gate, what))

    for zz in (True, False):
        book = "Heisenberg" if zz else "XY"
        for n, js in profiles:
            bonds = _bonds(js)
            h = S.se_hamiltonian_int(n, bonds, zz)
            chi = S._charpoly(h)
            note("G2", _is_squarefree(chi), (book, n, js))
            for seat in (0, n - 1):
                note("G1", S.blind_truth(n, bonds, seat, zz) == 0,
                     (book, n, js, seat))
            for seat in range(n):
                chi_l = S._charpoly(_sub(h, 0, seat)) if seat > 0 else ONE
                chi_r = S._charpoly(_sub(h, seat + 1, n)) if seat < n - 1 else ONE
                note("G3", _is_squarefree(chi_l) and _is_squarefree(chi_r),
                     (book, n, js, seat))
                shared = _poly_gcd(chi_l, chi_r)
                deg = len(shared) - 1
                note("G4", S._poly_gcd_degree(shared, chi) == deg,
                     (book, n, js, seat))
                note("G5", deg == S.blind_truth(n, bonds, seat, zz),
                     (book, n, js, seat))

    print(f"zero-free profiles swept: {len(profiles)}, run on both books, "
          f"so {2 * len(profiles)} (book, profile) pairs, N = 2..8")
    print(f"composition: 2 uniform families per N (all-1 and all-2), every")
    print(f"signed product over (1, -1, 2, -3) at N = 3..6, and 300 random")
    print(f"irregular profiles at N = 3..8")
    print()
    print("each gate runs over its OWN index set, so the totals differ:")
    for gate, over in (("G1", "(book, profile, END seat), 2 ends per profile"),
                       ("G2", "(book, profile)"),
                       ("G3", "(book, profile, seat)"),
                       ("G4", "(book, profile, seat)"),
                       ("G5", "(book, profile, seat)")):
        bad, ok = tally[gate]
        print(f"  {gate}: pass {ok:6d}   FAIL {bad}   over {over}")
    print()
    print("first failures:", failures[:5] if failures else "none")


def run_commutant():
    """G6..G7: the kernel is 1 + dim commutant(H|_W), and when that is 1 + blind."""
    print("THEOREM A, THE KERNEL AS A COMMUTANT.  dim ker L_SE(j) =")
    print("1 + dim commutant(H restricted to the Krylov complement W).  Right")
    print("side never mentions a chain, a zero bond or a simplicity fence.")
    print("The span identity dim ker = 1 + blind is the special case where")
    print("H|_W has a SIMPLE spectrum, since blind(j) = dim W and a commutant")
    print("is the sum of squared multiplicities.  The framing is the repo's")
    print("(CAUGHT_ERRORS 2026-08-24, THE_SEAT_THAT_CUTS section 5, the F4 seat")
    print("sub-bullets); what is computed here is that ONE seat forces the blocks.")
    print()
    print("  G6  the theorem, at every seat of the twenty graphs, both books,")
    print("      with BOTH sides taken over Q (neither side a one-sided rank)")
    print("  G6b the committed GF(p) kernel route agrees with the rational one")
    print("  G7  the span identity holds exactly where dim commutant(H|_W)")
    print("      equals dim W, and fails exactly where it exceeds it")
    print()
    print(f"{'graph':38s} {'book':10s} {'seat':4s} {'blind':5s} {'ker':4s} "
          f"{'1+blind':7s} {'1+comm':6s} span")
    thm = [0, 0]
    routes = [0, 0]
    span = [0, 0]
    zero_bond_fail = 0
    zero_bond_holds = 0
    graph_fail = {True: set(), False: set()}
    for zz in (True, False):
        book = "Heisenberg" if zz else "XY"
        for name, n, bonds in S.DELETED_GRAPHS:
            for seat in range(n):
                h, basis = blind_basis(n, bonds, seat, zz)
                blind = len(basis)
                if blind != S.blind_truth(n, bonds, seat, zz):
                    raise AssertionError("blind basis disagrees with the count")
                comm = commutant_dim(restrict(h, basis))
                ker = kernel_dim_q(n, bonds, seat, zz)
                routes[ker == S.exact_kernel_dim(n, bonds, [seat], zz)] += 1
                thm[ker == 1 + comm] += 1
                ok = (ker == 1 + blind)
                span[ok] += 1
                if ok and any(j == 0 for (_, _, j) in bonds):
                    zero_bond_holds += 1
                if not ok:
                    graph_fail[zz].add(name)
                    if any(j == 0 for (_, _, j) in bonds):
                        zero_bond_fail += 1
                    print(f"{name:38s} {book:10s} {seat:<4d} {blind:<5d} "
                          f"{ker:<4d} {1 + blind:<7d} {1 + comm:<6d} NO")
    print()
    print(f"  G6:  pass {thm[1]}   FAIL {thm[0]}")
    print(f"  G6b: pass {routes[1]}   FAIL {routes[0]}")
    print(f"  G7: the span identity holds on {span[1]} of the "
          f"{span[0] + span[1]} (graph, book, seat) triples, and every one of")
    print(f"      the {span[0]} failures printed above is a case where 1 + comm")
    print(f"      is the kernel and 1 + blind is not")
    print()
    print(f"  is the ZERO BOND the discriminator?  No, and it misses in both")
    print(f"      directions: of the {span[0]} failing triples, {zero_bond_fail} carry a zero")
    print(f"      bond and {span[0] - zero_bond_fail} do not, while {zero_bond_holds} triples carry a zero bond")
    print(f"      and the identity HOLDS on them anyway.")
    print()
    print(f"  span failures by GRAPH: Heisenberg {len(graph_fail[True])} of 20, "
          f"XY {len(graph_fail[False])} of 20")
    only_xy = sorted(graph_fail[False] - graph_fail[True])
    only_zz = sorted(graph_fail[True] - graph_fail[False])
    print(f"  on XY and not on Heisenberg: {only_xy if only_xy else 'none'}")
    print(f"  on Heisenberg and not on XY: {only_zz if only_zz else 'none'}")


def run_chain():
    """G8: the corollary, the span identity on every zero-free chain."""
    print("COROLLARY, THE ZERO-FREE CHAIN.  Lemma J (classical for an unreduced")
    print("Jacobi matrix; here proved for the real symmetric case the sector")
    print("gives) makes the spectrum simple,")
    print("so every multiplicity in Theorem A is 1 and the commutant of H|_W is")
    print("diagonal: dim ker L_SE(j) = 1 + blind(j).  Gated end to end here,")
    print("the kernel by its own exact GF(p) rank and the count by the Krylov")
    print("rank, two routes meeting as integers.")
    print()
    print("  G8  dim ker L_SE(j) = 1 + blind(j) at every seat of every")
    print("      zero-free profile, both books")
    print()
    profiles = zero_free_profiles(nmax=7)
    tally = [0, 0]
    failures = []
    for zz in (True, False):
        book = "Heisenberg" if zz else "XY"
        for n, js in profiles:
            bonds = _bonds(js)
            for seat in range(n):
                blind = S.blind_truth(n, bonds, seat, zz)
                ker = S.exact_kernel_dim(n, bonds, [seat], zz)
                ok = (ker == 1 + blind)
                tally[ok] += 1
                if not ok:
                    failures.append((book, n, js, seat, blind, ker))
    print(f"zero-free profiles swept: {len(profiles)}, run on both books, "
          f"N = 2..7")
    print(f"(book, profile, seat) triples: {2 * sum(n for n, _ in profiles)}")
    print(f"  G8: pass {tally[1]}   FAIL {tally[0]}")
    print("first failures:", failures[:5] if failures else "none")


PARTS = [("lemma", run_lemma), ("commutant", run_commutant), ("chain", run_chain)]


def main():
    which = sys.argv[1] if len(sys.argv) > 1 else "all"
    chosen = PARTS if which == "all" else [p for p in PARTS if p[0] == which]
    if not chosen:
        print(f"unknown part {which!r}; parts: "
              f"{' | '.join(name for name, _ in PARTS)} | all")
        return 1
    for i, (name, fn) in enumerate(chosen):
        if i:
            print()
            print("-" * 72)
            print()
        fn()
    return 0


if __name__ == "__main__":
    sys.exit(main())
