#!/usr/bin/env python3
"""Derivation: the crossover mirror is the XZ-bond mirror turned by √(NinetyDegreeMirror).

Computational companion to docs/proofs/PROOF_CROSSOVER_MIRROR_SQRT_NINETY.md. Promotes
CrossoverMirrorSqrtNinetyClaim from Tier1Candidate to Tier1Derived: the √-of-90° is not a
measured coincidence, it is forced by the bond geometry, and each step is closed-form
algebra verified here bit-exact.

The chain of facts (all bit-exact):

  (a) X + Y = √2 · V·X·V†   with V = R_z(π/4) = exp(−iπZ/8).
      The crossover bond's lit operator is X rotated 45° about the Z axis.
      Hence H_cross = (X+Y)·Z = √2 · Ad_{V₀}(X·Z), V₀ = V on the lit site.

  (b) [V, Z] = 0   (V is generated by Z), so Ad_{V₀} commutes with the Z-dephasing
      dissipator D (every dephasing operator Z_l is fixed by V₀).

  (c) Therefore the whole Liouvillian transports:
          L_cross = Ad_{V₀} · L_{√2·XZ} · Ad_{V₀}⁻¹                         (exact)
      L_{H_cross} = Ad_{V₀} L_{√2 XZ} Ad_{V₀}⁻¹ since L_{Ad_U(H)} = Ad_U L_H Ad_U⁻¹, and
      D is Ad_{V₀}-invariant by (b). So any XZ-bond mirror Π_XZ transports to a crossover
      mirror Π_cross = Ad_{V₀} Π_XZ Ad_{V₀}⁻¹.

  (d) Ad_{V₀}² = Ad_{R_z(π/2)} = (X↦Y, Y↦−X) = the σ_x↔σ_y 90° rotation = the
      NinetyDegreeMirror. So Ad_{V₀} = √(NinetyDegreeMirror).

Reading: the crossover mirror differs from the XZ-bond mirror by exactly √(NinetyDegreeMirror),
because the crossover bond is the XZ bond with its lit operator rotated 45° about the dephasing
axis, half the 90° that takes X to Y, and that axis is fixed by the rotation so the transport
is exact. In gate language: the NinetyDegreeMirror is the S-gate's adjoint action, the transport
is the T-gate's, its square root.

Run:  PYTHONIOENCODING=utf-8 python simulations/crossover_mirror_derivation.py
"""
from __future__ import annotations

import sys
import numpy as np
from scipy.linalg import expm

sys.path.insert(0, 'simulations')
import framework as fw  # noqa: E402

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

I2 = np.eye(2, dtype=complex)
X = np.array([[0, 1], [1, 0]], dtype=complex)
Yp = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z = np.array([[1, 0], [0, -1]], dtype=complex)
PAULI = {0: I2, 1: X, 2: Z, 3: Yp}   # framework order [I, X, Z, Y]
LBL = {0: 'I', 1: 'X', 2: 'Z', 3: 'Y'}
GAMMA = 0.5

V = expm(-1j * (np.pi / 4) * Z / 2.0)        # R_z(π/4): the T-gate (up to global phase)
V_S = expm(-1j * (np.pi / 2) * Z / 2.0)      # R_z(π/2): the S-gate


def ad_single(U):
    """Ad_U: σ ↦ U σ U†, as a 4×4 matrix in the single-site [I,X,Z,Y] Pauli basis."""
    A = np.zeros((4, 4), dtype=complex)
    for cin in range(4):
        out = U @ PAULI[cin] @ U.conj().T
        for rout in range(4):
            A[rout, cin] = np.trace(PAULI[rout].conj().T @ out) / 2.0
    return A


def ad_operator_space(U_full, N):
    """Ad_{U_full} on N-qubit operator space, in the Pauli-string basis (vec then transform).

    For O ↦ U O U†, the vec-form superoperator (row-major vec) is U ⊗ conj(U); transform to the
    Pauli-string basis with the same V_pauli the Liouvillian uses, so it is basis-consistent.
    """
    d = 2 ** N
    sup_vec = np.kron(U_full, np.conj(U_full))
    Vp = fw._vec_to_pauli_basis_transform(N)
    return (Vp.conj().T @ sup_vec @ Vp) / d


def liouvillian_pauli(H, N):
    L = fw.lindbladian_z_dephasing(H, [GAMMA] * N)
    Vp = fw._vec_to_pauli_basis_transform(N)
    return (Vp.conj().T @ L @ Vp) / (2 ** N)


def main():
    print("Derivation: crossover mirror = XZ-bond mirror · √(NinetyDegreeMirror)  (γ=0.5)\n")

    AdV = ad_single(V)
    print("(a) the bond's lit operator is X rotated 45° about Z")
    r_a = np.linalg.norm(V @ X @ V.conj().T - (X + Yp) / np.sqrt(2))
    print(f"    V X V† = (X+Y)/√2 ?   residual {r_a:.2e}")
    print()

    print("(b) V commutes with the dephasing axis Z, so Ad_V fixes the dissipator")
    print(f"    ‖[V, Z]‖ = {np.linalg.norm(V @ Z - Z @ V):.2e}")
    print()

    print("(d) Ad_V² = the σ_x↔σ_y 90° rotation = the NinetyDegreeMirror (S-gate adjoint)")
    light = [1, 3]
    sq = (AdV @ AdV)[np.ix_(light, light)]
    ninety = np.array([[0, -1], [1, 0]], dtype=complex)
    print(f"    Ad_V²|_light = [[0,−1],[1,0]] ?   residual {np.linalg.norm(sq - ninety):.2e}")
    print(f"    Ad_V² = Ad_(S-gate) on the full single-site space ?   "
          f"residual {np.linalg.norm(AdV @ AdV - ad_single(V_S)):.2e}")
    print()

    print("(c) the Liouvillian transports exactly: L_cross = Ad_{V₀} L_{√2·XZ} Ad_{V₀}⁻¹")
    for N in (2, 3, 4):
        d = 2 ** N
        Hc = np.zeros((d, d), dtype=complex)
        Hx = np.zeros((d, d), dtype=complex)
        for i in range(N - 1):
            Hc += fw.site_op(N, i, 'X') @ fw.site_op(N, i + 1, 'Z') \
                + fw.site_op(N, i, 'Y') @ fw.site_op(N, i + 1, 'Z')
            Hx += np.sqrt(2) * fw.site_op(N, i, 'X') @ fw.site_op(N, i + 1, 'Z')
        Lc = liouvillian_pauli(Hc, N)
        Lx = liouvillian_pauli(Hx, N)
        # V₀ = V on every lit (left-endpoint) site 0..N−2, identity on the last (Z-only) site.
        U_full = np.array([[1]], dtype=complex)
        for s in range(N):
            U_full = np.kron(U_full, V if s < N - 1 else I2)
        Ad0 = ad_operator_space(U_full, N)
        resid = np.linalg.norm(Lc - Ad0 @ Lx @ np.linalg.inv(Ad0))
        print(f"    N={N}: residual {resid:.2e}")
    print()
    print("All bit-exact: the √-of-90° is forced by the geometry, not measured. Tier1Derived.")


if __name__ == "__main__":
    main()
