#!/usr/bin/env python3
"""Door 1: pin the F87 obstruction to its coding-theory object (scout, 2026-06-05).

The §7.7 GF(2)[x] picture says an odd 𝔽₂-relation among a pair's window-shifts {x^w p1} ∪ {x^w p2}
is a syzygy q_A p1 = q_B p2, and with g = gcd(p1,p2), a = p2/g, b = p1/g (gcd(a,b)=1) every syzygy is
    (q_A, q_B) = (a·s, b·s),  s in GF(2)[x],
so the dependence-vectors form the QUASI-CYCLIC code generated by the interleaved word (a | b) under
the shift, and the obstruction = its minimum ODD weight. This scout verifies that dictionary against
the direct shift-dependence search, reads off the generator's structure (degrees, popcounts,
(1+x)-valuations, whether a, b are repunits), and dumps facts for the named-code identification.

A repunit R_m = 1 + x + ... + x^{m} = (x^{m+1} + 1)/(1 + x); the extremal family's quotients are
repunits, which is the first clue toward a named cyclic-code family.
"""
from __future__ import annotations

import sys
from itertools import product, combinations, combinations_with_replacement
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))
import framework as fw

DIAG = {"I", "Z"}


# ---- GF(2)[x] arithmetic (bit j = coeff of x^j) ----
def deg(p):
    return p.bit_length() - 1


def gf2_mul(a, b):
    r = 0
    while b:
        if b & 1:
            r ^= a
        b >>= 1
        a <<= 1
    return r


def gf2_divmod(a, b):
    q, db = 0, deg(b)
    while a and deg(a) >= db:
        sh = deg(a) - db
        q ^= 1 << sh
        a ^= b << sh
    return q, a


def gf2_gcd(a, b):
    while b:
        a, b = b, gf2_divmod(a, b)[1]
    return a


def popcount(x):
    return bin(x).count("1")


def valuation_1px(p):
    """(1+x)-adic valuation: how many times (1+x)=0b11 divides p."""
    v = 0
    while p and popcount(p) % 2 == 0:
        p = gf2_divmod(p, 0b11)[0]
        v += 1
    return v


def repunit(m):
    """R_m = 1 + x + ... + x^m  (m+1 ones)."""
    return (1 << (m + 1)) - 1


def is_repunit_shift(p):
    """Is p a shift x^j · R_m of a repunit (a solid run of 1-bits)? Return (m+1, j) or None."""
    if p == 0:
        return None
    j = (p & -p).bit_length() - 1          # lowest set bit
    q = p >> j
    length = popcount(q)
    if q == (1 << length) - 1:              # solid run
        return (length, j)
    return None


def min_odd_dependence(masks):
    """Minimum odd-cardinality subset of masks that XORs to 0 (the obstruction)."""
    masks = sorted(set(masks))
    for size in range(3, len(masks) + 1, 2):
        for combo in combinations(masks, size):
            x = 0
            for m in combo:
                x ^= m
            if x == 0:
                return size
    return 0


def qc_min_odd_weight(a, b, W):
    """Minimum odd weight of the WINDOW-truncated quasi-cyclic code {(a·s, b·s)}: s ranges over
    exactly the multipliers whose products a·s, b·s still fit in W windows (deg <= W-1), matching
    the windowed shift set. This is the obstruction, by definition of the odd dependences of S."""
    max_s_deg = (W - 1) - max(deg(a), deg(b))
    if max_s_deg < 0:
        return 0
    best = 0
    for s in range(1, 1 << (max_s_deg + 1)):
        w = popcount(gf2_mul(a, s)) + popcount(gf2_mul(b, s))
        if w % 2 == 1 and (best == 0 or w < best):
            best = w
    return best


def cell_terms(k):
    out = []
    for t in product("IXYZ", repeat=k):
        if all(L == "I" for L in t):
            continue
        if fw.klein_index(t) != (0, 1):
            continue
        if not any(L not in DIAG for L in t):
            continue
        m = 0
        for i, L in enumerate(t):
            if L in ("X", "Y"):
                m |= 1 << i
        out.append(("".join(t), m, sum(c == "Y" for c in t) % 2))
    return out


def main():
    print("=" * 96)
    print("F87 obstruction as a coding-theory object: the quasi-cyclic syzygy code <(a,b)>")
    print("=" * 96)

    for k in (4, 5, 6):
        N = 2 * k
        W = N - k + 1
        terms = cell_terms(k)
        dict_ok = True
        gen_is_repunit = 0
        gen_total = 0
        worst = None
        max_obs = 0
        for (l1, p1, y1), (l2, p2, y2) in combinations_with_replacement(terms, 2):
            if y1 != y2 or p1 == p2:
                continue
            S = {p1 << w for w in range(W)} | {p2 << w for w in range(W)}
            obs = min_odd_dependence(S)
            if obs == 0:
                continue  # soft
            g = gf2_gcd(p1, p2)
            a = gf2_divmod(p2, g)[0]
            b = gf2_divmod(p1, g)[0]
            # QC code min odd weight (s small: deg up to W-1 covers the windows)
            qc = qc_min_odd_weight(a, b, W)
            if qc != obs:
                dict_ok = False
            gen_total += 1
            if is_repunit_shift(a) and is_repunit_shift(b):
                gen_is_repunit += 1
            if obs > max_obs:
                max_obs = obs
                worst = (l1, l2, p1, p2, g, a, b, obs)

        print(f"\n  k={k} (N={N}, W={W}):")
        print(f"    dictionary  obstruction == min-odd-weight of QC code <(a,b)>:  {dict_ok}")
        print(f"    generator (a,b) both repunit-shifts:  {gen_is_repunit}/{gen_total} hard pairs")
        l1, l2, p1, p2, g, a, b, obs = worst
        print(f"    extremal {l1}+{l2}: p1={p1:0{k}b} p2={p2:0{k}b}  g={g:b}")
        print(f"      a=p2/g={a:b} (deg {deg(a)}, wt {popcount(a)}, repunit {is_repunit_shift(a)}, v1+x {valuation_1px(a)})")
        print(f"      b=p1/g={b:b} (deg {deg(b)}, wt {popcount(b)}, repunit {is_repunit_shift(b)}, v1+x {valuation_1px(b)})")
        print(f"      obstruction = {obs} = 2k-3 = {2*k-3}")

    # The single-mask cyclic code <p> and its (1+x)-filtration (the named-code clue).
    print("\n" + "-" * 96)
    print("  single-mask cyclic code <p> (length N): min distance vs (1+x)-valuation")
    print("-" * 96)
    for k in (4, 5, 6):
        N = 2 * k
        for label, p in [("extremal a=x+x^{k-1}", (1 << 1) | (1 << (k - 1))),
                         ("repunit R_{k-2}", repunit(k - 2)),
                         ("full mask 1..1", (1 << k) - 1)]:
            # min weight nonzero multiple of p of degree < N  = d(<p>)
            best = N + 1
            for q in range(1, 1 << (N - deg(p))):
                w = popcount(gf2_mul(p, q))
                if 0 < w < best:
                    best = w
            print(f"    k={k} N={N}  {label:24s} p={p:b}  v1+x={valuation_1px(p)}  d(<p>)={best}")

    print("\n  reading: if dictionary holds, the obstruction IS a quasi-cyclic-code minimum odd weight")
    print("  and the generators are repunit-shifts -> a named cyclic-code family is the next question")
    print("  (Reed-Muller / BCH via the (1+x)-filtration; MacWilliams for the size distribution).")


if __name__ == "__main__":
    main()
