#!/usr/bin/env python3
"""[RETRACTED 2026-06-05] This scout's headline claim -- dim(ker L) = 2^(N-r) -- is WRONG. It held only
for the HARD pairs tested here; for SOFT / partial-support pairs dim(ker L) exceeds 2^(N-r), and the
actual conserved-sector count is letter-dependent (XX+YY cancels the |00>-|11> channel, so the real
hopping graph is sparser than the mask). The mask-span rank is NOT a clean spectral fingerprint. See
simulations/f87_rank_footprint.py for the breakdown and PROOF_F103 §7.10 retraction. The size-perp-rank
NULL (part 3) still stands. Kept for the honest record.

Door 3 deep: verify the agent's result -- the mask SPAN-RANK reaches the spectrum, the size does not.

The spectral-deepening agent found (rigorously, with letter controls) that of the GF(2) structure of the
masks, only TWO coarse invariants leave a letter-independent fingerprint on the Liouvillian:
  - the (1+x)-valuation  -> hard/soft (known);
  - the span-rank r of the windowed mask set {x^w p_i} -> a conserved-sector multiplicity 2^(N-r) (new),
the # connected components of H's computational-basis hopping graph = dim of the diagonal commutant.
The obstruction SIZE (and deg(g_rest)) reach NOTHING letter-independent -- they live in the
letter-dependent off-diagonal weights, so they stay combinatorial.

This script verifies, bit-exact and myself: (1) # hopping-graph components = 2^(N-r); (2) dim(ker L) =
2^(N-r), letter-INDEPENDENT (two letter realizations of one mask-pair give the same kernel); (3) the
NULL: at fixed r the obstruction size varies, so the size is not a function of the spectral handle r.
"""
from __future__ import annotations

import sys
from itertools import combinations
from pathlib import Path

import numpy as np

if sys.platform == "win32":
    try: sys.stdout.reconfigure(encoding="utf-8")
    except Exception: pass

SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))
import framework as fw
from framework.pauli import _build_kbody_chain
from framework.lindblad import lindbladian_pauli_dephasing

def popcount(x): return bin(x).count("1")

def gf2_rank(vectors):
    basis = []
    for v in vectors:
        for b in basis:
            v = min(v, v ^ b)
        if v: basis.append(v); basis.sort(reverse=True)
    return len(basis)

def windowed_masks(mask, k, N):
    return [mask << w for w in range(N - k + 1)]

def n_components(masks, N):
    """# orbits of the flip-subgroup generated by `masks` acting on 2^N basis states."""
    parent = list(range(1 << N))
    def find(a):
        while parent[a] != a: parent[a] = parent[parent[a]]; a = parent[a]
        return a
    for i in range(1 << N):
        for m in masks:
            j = i ^ m
            ri, rj = find(i), find(j)
            if ri != rj: parent[ri] = rj
    return len({find(i) for i in range(1 << N)})

def mask_of(letters):
    m = 0
    for i, L in enumerate(letters):
        if L in ("X", "Y"): m |= 1 << i
    return m

def min_odd_dependence(masks):
    masks = sorted(set(masks))
    for size in range(3, len(masks) + 1, 2):
        for combo in combinations(masks, size):
            x = 0
            for mm in combo: x ^= mm
            if x == 0: return size
    return 0

def dim_ker_L(letter_terms, N, gamma=0.05):
    H = _build_kbody_chain(N, [tuple(t) + (1.0,) for t in letter_terms])
    L = lindbladian_pauli_dephasing(H, [gamma] * N, dephase_letter='Z')
    ev = np.linalg.eigvals(L)
    return int(np.sum(np.abs(ev) < 1e-8))


def main():
    print("=" * 88)
    print("Door 3 deep: the span-rank reaches the spectrum (2^(N-r)); the obstruction size does not")
    print("=" * 88)

    # (1)+(2): rank -> components -> dim(ker L), letter-independent. Two hard pairs at k=3, N=4.
    print("\n  (1)+(2) rank r -> #components = 2^(N-r) = dim(ker L), letter-independent:")
    cases = [
        # (label, two letter-term realizations of the SAME X/Y mask-pair)
        ("XYI+YIX masks {110,101}", [[('X','Y','I'),('Y','I','X')], [('Y','X','I'),('X','I','Y')]]),
        ("XXI+IXX masks {110,011}", [[('X','X','I'),('I','X','X')], [('Y','Y','Z'),('Z','Y','Y')]]),
    ]
    N = 4
    for label, realizations in cases:
        masks = set()
        for t in realizations[0]:
            masks.add(mask_of(t))
        flips = []
        k = len(realizations[0][0])
        for mm in masks: flips += windowed_masks(mm, k, N)
        r = gf2_rank(flips)
        comps = n_components(flips, N)
        kerdims = [dim_ker_L(real, N) for real in realizations]
        ok = (comps == (1 << (N - r))) and all(kd == comps for kd in kerdims)
        print(f"    {label}: r={r}  2^(N-r)={1<<(N-r)}  #components={comps}  "
              f"dim(ker L) per letter realization={kerdims}  {'OK' if ok else 'MISMATCH'}")

    # (3) THE NULL: at fixed rank r, the obstruction size varies (size is not a function of r).
    print("\n  (3) NULL: at fixed span-rank r, the obstruction size spans multiple values:")
    for k in (4, 5):
        N = 2 * k
        masks_all = [m for m in range(1, 1 << k) if popcount(m) % 2 == 0]
        by_r = {}
        for p1, p2 in combinations(masks_all, 2):
            flips = windowed_masks(p1, k, N) + windowed_masks(p2, k, N)
            r = gf2_rank(flips)
            obs = min_odd_dependence(set(flips))
            if obs == 0: continue
            by_r.setdefault(r, set()).add(obs)
        for r in sorted(by_r):
            sizes = sorted(by_r[r])
            flag = "  <- size varies at fixed r" if len(sizes) > 1 else ""
            print(f"    k={k}: rank r={r} -> obstruction sizes {sizes}{flag}")

    print("\n  reading: the rank reaches the kernel (2^(N-r), letter-stable); the obstruction size is")
    print("  independent of r, confirming it stays combinatorial and never reaches the spectrum.")


if __name__ == "__main__":
    main()
