#!/usr/bin/env python3
"""The full mirror group on coherence space: there is NO order-48 S3 |x| D4.

Arc: linear_s3_mirror_completion. PROOF_PI_FACTORS_AS_R_TIMES_D.md sec.5 asks whether the letter
permutations and the mirror group D4 = <R, D> assemble into an S3 |x| D4 of order 48. This
verifier computes every order rather than assuming 48.

THE RESULT:
  * The letter-S3 EXISTS as superoperators: <h_zx, t_yz> = 6, generated by the INVOLUTIVE
    Clifford transpositions (Hadamard for X<->Z, (Y+Z)/sqrt2 for Y<->Z; both order 2, their
    product order 3). (A rotation like R_x(pi/2) is order 4 and generates the order-24
    Clifford group instead -- that is NOT the mirror-group S3.)
  * The S3 does NOT normalize D4: h_zx . R . h_zx^-1 = the one-sided multiplication by Z^(x)N,
    outside the eight elements of <R, D> (stage 3).
  * The closure <R, D, h_zx, t_yz> has order 768/gcd(N,4) = 768, 384, 768, 192, 768 at
    N = 1..5, projectively 192 at every N, never 48 (stage 2; exact monomial closure on the
    Pauli strings at N = 1..5, and the dense Kronecker-built float closure at N = 1..4).
    The reason: every generator is the N-fold tensor power of a one-site superoperator, so
    g -> g^(x)N maps the N = 1 group (order 768, scalars = the fourth roots of unity) onto the
    N-site group, and the kernel is the scalars w with w^N = 1. The sub-closure <R, D, h_zx>
    has order 128/gcd(N,2). The one-sided multiplications rho -> rho S inside the closure are
    up to a global phase the four global ones, S in {I, X, Y, Z}^(x)N, at every N.
  * The single S3 (the letter permutation) acts faithfully on the SIGN-BLIND diagonals
    {Q_X,Q_Y,Q_Z} (orbit 3, full S3); the palindromizers {Pi_X,Pi_Y,Pi_Z} carry the Clifford
    signs (a larger orbit), which is why there were never "two S3's": there is one.

Row-stacking (C-order) vec, kron(A,B): rho -> A rho B^T. Pi from framework.symmetry
.build_pi_full (Pauli basis) lifted to coherence via M = _vec_to_pauli_basis_transform and
conj-aligned to the typed convention Pi_Z = R.D. Reuses the verified building blocks of
one_diagonal_mirror_group.py. Self-validating: ALL STAGES PASS only if every assert holds.
"""
import sys
from math import gcd
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from framework.symmetry import build_pi_full                       # noqa: E402
from framework.pauli import _vec_to_pauli_basis_transform          # noqa: E402
from one_diagonal_mirror_group import (                            # noqa: E402
    swap_perm, Q_diag, ad_unitary, group_closure, orbit_of, xn, HAD, TOL,
)

MATCH = 1e-8

X1 = np.array([[0, 1], [1, 0]], dtype=complex)
Y1 = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z1 = np.array([[1, 0], [0, -1]], dtype=complex)
# the INVOLUTIVE letter-transposition Cliffords (reflections, order 2 as Ad):
T_YZ = (Y1 + Z1) / np.sqrt(2.0)     # Y<->Z, X->-X
T_XY = (X1 + Y1) / np.sqrt(2.0)     # X<->Y, Z->-Z
# (T_XZ = Hadamard (HAD): X<->Z, Y->-Y -- already an involution)


def pi_coh(N, letter):
    """Pi_letter on coherence space, conj-aligned to the typed convention Pi_Z = R.D.

    build_pi_full uses the opposite i-phase (Y->+iZ), so its Pi is Pi^-1 relative to R.D;
    complex-conjugating the signed permutation inverts the order-4 element back to Pi_Z.
    (Diagnosed via the Stage-0 gate: dev 1.0 -> 0. D.Pi_Z.D = Pi_Y holds in both conventions.)"""
    M = _vec_to_pauli_basis_transform(N)
    Minv = M.conj().T / (2 ** N)
    return M @ build_pi_full(N, letter).conj() @ Minv


def ops(N):
    """R, D (the D4 core) and the involutive letter-transposition superoperators on coherence space."""
    d = 2 ** N
    Id = np.eye(d, dtype=complex)
    R = np.kron(Id, xn(N))            # R: rho -> rho F,  F = X^(x)N  (ONE-SIDED)
    D = swap_perm(N)                  # D: rho -> rho^T
    h_zx = ad_unitary(N, HAD)         # X<->Z involution
    t_yz = ad_unitary(N, T_YZ)        # Y<->Z involution
    t_xy = ad_unitary(N, T_XY)        # X<->Y involution
    return R, D, h_zx, t_yz, t_xy


def order_of(g, maxo=64):
    P = np.eye(g.shape[0], dtype=complex)
    for k in range(1, maxo + 1):
        P = P @ g
        if np.max(np.abs(P - np.eye(g.shape[0]))) < MATCH:
            return k
    return None


# ============================ Stage 0: conventions + D4 core (the gate) ============================
def stage0_gate(N=2):
    print(f"Stage 0 (gate): Pi_Z=R.D, D.Pi_Z.D=Pi_Y, |<R,D>|=8 on coherence space (N={N}):")
    R, D, *_ = ops(N)
    PiZ, PiY = pi_coh(N, "Z"), pi_coh(N, "Y")
    dev_fac = np.max(np.abs(PiZ - R @ D))
    dev_inv = np.max(np.abs(D @ PiZ @ D - PiY))
    d4 = group_closure([R, D], (2 ** N) ** 2)
    print(f"   |Pi_Z - R.D| = {dev_fac:.2e}   |D.Pi_Z.D - Pi_Y| = {dev_inv:.2e}   |<R,D>| = {len(d4)}")
    assert dev_fac < MATCH, "GATE: Pi_Z != R.D -- coherence-space Pi transform misconventioned."
    assert dev_inv < MATCH, "GATE: D.Pi_Z.D != Pi_Y -- dihedral inversion broken."
    assert len(d4) == 8, f"GATE: |<R,D>| = {len(d4)} != 8 (D4 core)."
    print("   [0] conventions consistent; D4 core = 8. OK")


# ============================ Stage 1: the letter-S3 EXISTS (order 6) ============================
def stage1_the_s3(N=2):
    print(f"\nStage 1: the letter-S3 from INVOLUTIVE transpositions (N={N}):")
    R, D, h_zx, t_yz, t_xy = ops(N)
    dim = (2 ** N) ** 2
    print(f"   element orders: ord(h_zx)={order_of(h_zx)} ord(t_yz)={order_of(t_yz)} ord(t_xy)={order_of(t_xy)}")
    n_s3 = len(group_closure([h_zx, t_yz], dim))
    n_three = len(group_closure([h_zx, t_yz, t_xy], dim))
    n_v4 = len(group_closure([D, h_zx], dim))
    print(f"   |<h_zx, t_yz>|        = {n_s3}   (S3: two involutions, product order 3)")
    print(f"   |<h_zx, t_yz, t_xy>|  = {n_three}  (all three involutive swaps -> the Clifford group; "
          f"the 3rd swap is NOT in the S3 of the first two, it differs by a Pauli sign)")
    print(f"   |<D, h_zx>|           = {n_v4}   (the honest dephase-swaps {{I,D,H,Q_zx}} = Klein-V4, abelian)")
    assert order_of(h_zx) == 2 and order_of(t_yz) == 2, "the letter transpositions must be involutions."
    assert n_s3 == 6, f"<h_zx,t_yz> = {n_s3}, expected 6 (the letter-S3)."
    assert n_three == 24, f"<h_zx,t_yz,t_xy> = {n_three}, expected 24 (Clifford group)."
    assert n_v4 == 4, f"<D,h_zx> = {n_v4}, expected 4 (Klein-V4)."
    print("   [1] the letter-S3 exists (order 6); all three swaps together give Clifford-24. OK")


# ============================ Stage 2: the closure order is 768/gcd(N,4), NOT 48 ============================
LETTER_MATS = [np.eye(2, dtype=complex), X1, Y1, Z1]


def _letter_phase(m):
    """m = i^k * sigma_c exactly (up to float) -> (c, k)."""
    for c in range(4):
        for k in range(4):
            if np.max(np.abs(m - (1j) ** k * LETTER_MATS[c])) < MATCH:
                return c, k
    raise ValueError("not a phased Pauli letter")


def _one_site_table(f):
    """one-site superoperator f on 2x2 matrices -> [letter -> (image letter, phase exponent)]."""
    return [_letter_phase(f(LETTER_MATS[a])) for a in range(4)]


LETTER_PRODUCT = [[_letter_phase(a @ b) for b in LETTER_MATS] for a in LETTER_MATS]   # a.b = i^k sigma_c

ONE_SITE = {
    "R": _one_site_table(lambda P: P @ X1),                          # rho -> rho X
    "D": _one_site_table(lambda P: P.T),                             # rho -> rho^T
    "h_zx": _one_site_table(lambda P: HAD @ P @ HAD.conj().T),
    "t_yz": _one_site_table(lambda P: T_YZ @ P @ T_YZ.conj().T),
}


def monomial(N, table):
    """The N-site generator g^(x)N as an exact monomial map on Pauli strings:
    (image index per string, phase exponent mod 4 per string). Integers only."""
    img, ph = [], []
    for idx in range(4 ** N):
        j, k = 0, 0
        for s in range(N):
            c, kk = table[(idx >> (2 * s)) & 3]
            j |= c << (2 * s)
            k += kk
        img.append(j)
        ph.append(k % 4)
    return tuple(img), tuple(ph)


def exact_closure(gens):
    n = len(gens[0][0])
    e = (tuple(range(n)), (0,) * n)
    seen, frontier = {e}, [e]
    while frontier:
        nxt = []
        for gi, gp in frontier:
            for hi, hp in gens:                     # h o g
                y = (tuple(hi[gi[x]] for x in range(n)), tuple((gp[x] + hp[gi[x]]) % 4 for x in range(n)))
                if y not in seen:
                    seen.add(y)
                    nxt.append(y)
        frontier = nxt
    return seen


def scalars(G):
    ident = tuple(range(len(next(iter(G))[0])))
    return {gp[0] for gi, gp in G if gi == ident and len(set(gp)) == 1}


def projective_order(G):
    return len({(gi, tuple((p - gp[0]) % 4 for p in gp)) for gi, gp in G})


def stage2_closure_order(Ns=(1, 2, 3, 4, 5), float_Ns=(1, 2, 3, 4)):
    print(f"\nStage 2: the closure order is 768/gcd(N,4), NOT 48 (exact at N={Ns}, float route at N={float_Ns}):")
    for N in Ns:
        g = {k: monomial(N, t) for k, t in ONE_SITE.items()}
        g3 = exact_closure([g["R"], g["D"], g["h_zx"]])
        g4 = exact_closure([g["R"], g["D"], g["h_zx"], g["t_yz"]])
        n_sc, n_proj = len(scalars(g4)), projective_order(g4)
        print(f"   N={N}: |<R,D,h_zx>| = {len(g3):4d} (128/gcd(N,2) = {128 // gcd(N, 2)})   "
              f"|<R,D,h_zx,t_yz>| = {len(g4):4d} (768/gcd(N,4) = {768 // gcd(N, 4)}, 96*2^N = {96 * 2 ** N})   "
              f"scalars = {n_sc}   projective = {n_proj}")
        # the law, and the reason for it: g -> g^(x)N maps the N=1 group (order 768, scalars mu_4) onto
        # the N-site group, with kernel the scalars w, w^N = 1; so |G_N| = 192 * |mu_4^N| = 768/gcd(N,4)
        assert len(g4) == 768 // gcd(N, 4), f"<R,D,h_zx,t_yz> = {len(g4)} != 768/gcd(N,4)"
        assert n_proj == 192, f"projective order {n_proj} != 192"
        assert n_sc == 4 // gcd(N, 4), f"scalar subgroup {n_sc} != |mu_4^N| = {4 // gcd(N, 4)}"
        assert len(g3) == 128 // gcd(N, 2), f"<R,D,h_zx> = {len(g3)} != 128/gcd(N,2)"
        assert len(g4) != 48, "the order-48 premise would hold -- revisit if this ever fires."
        if N in float_Ns:  # second route: the dense Kronecker-built superoperators of ops(), float closure
            R, D, h_zx, t_yz, _ = ops(N)
            dim = (2 ** N) ** 2
            n_f = len(group_closure([R, D, h_zx, t_yz], dim))
            n_loose = len(group_closure([R, D, h_zx, t_yz], dim, tol=1e-3))
            n_f3 = len(group_closure([R, D, h_zx], dim))
            print(f"        float route: {n_f3}, {n_f} (tol=1e-3: {n_loose})")
            assert (n_f3, n_f, n_loose) == (len(g3), len(g4), len(g4)), "float and exact routes disagree"
    print("   [2] 768/gcd(N,4) = 768, 384, 768, 192, ...; projectively 192 at every N; never 48. "
          "96*2^N meets it only at N = 2, 3. OK")


# ============================ Stage 3: the S3 does not normalize D4; the one-sided part ============================
def stage3_R_not_normalized(Ns=(1, 2, 3, 4, 5)):
    print(f"\nStage 3: h_zx R h_zx^-1 = rho -> rho Z^(x)N lies outside D4; the one-sided multiplications "
          f"in the closure are the four global ones:")
    for N in (2, 3):
        R, D, h_zx, *_ = ops(N)
        dim = (2 ** N) ** 2
        d = 2 ** N
        Zn = Z1
        for _ in range(N - 1):
            Zn = np.kron(Zn, Z1)
        R_Z = np.kron(np.eye(d, dtype=complex), Zn)
        conj = h_zx @ R @ np.linalg.inv(h_zx)
        dev = np.max(np.abs(conj - R_Z))
        in_d4 = any(np.max(np.abs(conj - e)) < MATCH for e in group_closure([R, D], dim))
        print(f"   (N={N}) h_zx . R . h_zx^-1 = (rho -> rho Z^(x)N)?  dev = {dev:.2e}   in D4=<R,D>? {in_d4}")
        assert dev < MATCH, "h_zx . R . h_zx^-1 is not the one-sided Z^(x)N multiplication."
        assert not in_d4, "the image lands in D4 -- then the S3 WOULD normalize D4 (revisit)."
    for N in Ns:
        g = {k: monomial(N, t) for k, t in ONE_SITE.items()}
        g4 = exact_closure([g["R"], g["D"], g["h_zx"], g["t_yz"]])
        one_sided = set()
        for S in range(4 ** N):              # rho -> i^k rho S, for every Pauli string S
            rs = monomial_right(N, S)
            for k in range(4):
                if (rs[0], tuple((p + k) % 4 for p in rs[1])) in g4:
                    one_sided.add(S)
        labels = sorted("".join("IXYZ"[(S >> (2 * s)) & 3] for s in range(N)) for S in one_sided)
        print(f"   N={N}: one-sided multiplications rho -> rho S in the closure: S in {labels}")
        assert labels == sorted(L * N for L in "IXYZ"), "the one-sided part is not {I,X,Y,Z}^(x)N"
    print("   [3] the letter S3 does not normalize D4 -> no semidirect order-48; the one-sided part stays")
    print("       the four global flips at every N. OK")


def monomial_right(N, S):
    """rho -> rho S for the Pauli string S, as an exact monomial map."""
    img, ph = [], []
    for idx in range(4 ** N):
        j, k = 0, 0
        for s in range(N):
            c, kk = LETTER_PRODUCT[(idx >> (2 * s)) & 3][(S >> (2 * s)) & 3]
            j |= c << (2 * s)
            k += kk
        img.append(j)
        ph.append(k % 4)
    return tuple(img), tuple(ph)


# ============================ Stage 4: one S3, the diagonals vs the palindromizers ============================
def stage4_one_s3(N=2):
    print(f"\nStage 4: ONE S3, acting on the sign-blind diagonals and the signed palindromizers (N={N}):")
    R, D, h_zx, t_yz, t_xy = ops(N)
    dim = (2 ** N) ** 2
    s3 = group_closure([h_zx, t_yz], dim)
    Qs = [Q_diag(N, L) for L in ("X", "Y", "Z")]
    labels = ["X", "Y", "Z"]
    orbit_Q = orbit_of(Q_diag(N, "Z"), s3)
    orbit_Pi = orbit_of(pi_coh(N, "Z"), s3)
    # unsigned permutations of the diagonals induced by the S3:
    perms = set()
    for g in s3:
        ginv = np.linalg.inv(g)
        img = []
        for q in Qs:
            c = g @ q @ ginv
            hit = next((lab for lab, q2 in zip(labels, Qs)
                        if np.max(np.abs(c - q2)) < MATCH or np.max(np.abs(c + q2)) < MATCH), "?")
            img.append(hit)
        perms.add(tuple(img))
    print(f"   |S3| = {len(s3)}; orbit(Q_Z) = {len(orbit_Q)} (sign-blind diagonals), "
          f"orbit(Pi_Z) = {len(orbit_Pi)} (signed palindromizers)")
    print(f"   S3 permutes {{Q_X,Q_Y,Q_Z}} as {len(perms)} permutations (6 = full S3)")
    assert len(orbit_Q) == 3, f"Q_Z orbit = {len(orbit_Q)}, expected 3."
    assert len(perms) == 6, f"S3 permutes Q as {len(perms)}, expected the full S3 (6)."
    print("   [4] one S3: faithful on the diagonals (orbit 3, full S3); the palindromizers carry signs")
    print(f"       (orbit {len(orbit_Pi)}). There were never 'two S3's'. OK")


if __name__ == "__main__":
    for N in (2, 3):
        print(f"################################  N = {N}  ################################")
        stage0_gate(N)
        stage1_the_s3(N)
        stage4_one_s3(N)
        print()
    print("################################  N = 1..5  ################################")
    stage2_closure_order()
    stage3_R_not_normalized()
    print()
    print("ALL STAGES PASS: no order-48 S3|xD4 on coherence space. The letter-S3 (order 6) exists but does")
    print("not normalize D4; the closure <R,D,h_zx,t_yz> has order 768/gcd(N,4), projectively 192 at every N.")
