#!/usr/bin/env python3
"""The full mirror group on coherence space: there is NO finite order-48 S3 |x| D4.

Open arc: linear_s3_mirror_completion. PROOF_PI_FACTORS_AS_R_TIMES_D.md sec.5 names the
completion open with an "expected shape S3-letter-action |x| D4" (order 48); the SAME
section's addendum already corrected that to "the completion is O(2)-flavored ... NOT
finite". This verifier settles it on coherence space, gate-first, computing every order
rather than assuming 48.

THE RESULT (verified N=2,3, tolerance-robust 1e-10..1e-2, genuinely distinct elements):
  * The letter-S3 EXISTS as superoperators: <h_zx, t_yz> = 6, generated by the INVOLUTIVE
    Clifford transpositions (Hadamard for X<->Z, (Y+Z)/sqrt2 for Y<->Z; both order 2, their
    product order 3). (A rotation like R_x(pi/2) is order 4 and generates the order-24
    Clifford group instead -- that is NOT the mirror-group S3.)
  * But <R, D, h_zx, t_yz> = 96 * 2^N (384, 768), NOT 48. The S3 does NOT normalize the
    D4 = <R,D>: R = I (x) F is a ONE-SIDED multiplication, and under the letter-S3 it SPREADS
    (h_zx . R . h_zx^-1 = the one-sided multiplication by Z^(x)N, NOT in D4), generating the
    one-sided Pauli group -- the source of the 2^N growth.
  * So there is no faithful order-48 S3 |x| D4 subgroup of coherence-space superoperators;
    96*2^N is the discrete Clifford slice of the O(2) completion of sec.5's addendum. (Three
    distinct not-48 realizations: per-site monomial <r,d,h> = 128 (addendum, the Klein basis
    move h); coherence-space <R,D,h_zx,t_yz> = 96*2^N (THIS verifier, involutive Cliffords +
    the R-spread mechanism); continuous O(2) (addendum, the crossover-mirror thickening). This
    verifier completes sec.5 on coherence space; it does not overturn it -- the addendum already
    had per-site-128 and O(2). Only the sec.5-MAIN 'expected order-48' line is corrected.)
  * The single S3 (the letter permutation) acts faithfully on the SIGN-BLIND diagonals
    {Q_X,Q_Y,Q_Z} (orbit 3, full S3); the palindromizers {Pi_X,Pi_Y,Pi_Z} carry the Clifford
    signs (a larger orbit), which is why there were never "two S3's": there is one.

Row-stacking (C-order) vec, kron(A,B): rho -> A rho B^T. Pi from framework.symmetry
.build_pi_full (Pauli basis) lifted to coherence via M = _vec_to_pauli_basis_transform and
conj-aligned to the typed convention Pi_Z = R.D. Reuses the verified building blocks of
one_diagonal_mirror_group.py. Self-validating: ALL STAGES PASS only if every assert holds.
"""
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from framework.symmetry import build_pi_full                       # noqa: E402
from framework.pauli import _vec_to_pauli_basis_transform          # noqa: E402
from one_diagonal_mirror_group import (                            # noqa: E402
    swap_perm, Q_diag, ad_unitary, group_closure, orbit_of, xn, HAD, TOL,
)

MATCH = 1e-8

X1 = np.array([[0, 1], [1, 0]], dtype=complex)
Y1 = np.array([[0, -1j], [1j, 0]], dtype=complex)
Z1 = np.array([[1, 0], [0, -1]], dtype=complex)
# the INVOLUTIVE letter-transposition Cliffords (reflections, order 2 as Ad):
T_YZ = (Y1 + Z1) / np.sqrt(2.0)     # Y<->Z, X->-X
T_XY = (X1 + Y1) / np.sqrt(2.0)     # X<->Y, Z->-Z
# (T_XZ = Hadamard (HAD): X<->Z, Y->-Y -- already an involution)


def pi_coh(N, letter):
    """Pi_letter on coherence space, conj-aligned to the typed convention Pi_Z = R.D.

    build_pi_full uses the opposite i-phase (Y->+iZ), so its Pi is Pi^-1 relative to R.D;
    complex-conjugating the signed permutation inverts the order-4 element back to Pi_Z.
    (Diagnosed via the Stage-0 gate: dev 1.0 -> 0. D.Pi_Z.D = Pi_Y holds in both conventions.)"""
    M = _vec_to_pauli_basis_transform(N)
    Minv = M.conj().T / (2 ** N)
    return M @ build_pi_full(N, letter).conj() @ Minv


def ops(N):
    """R, D (the D4 core) and the involutive letter-transposition superoperators on coherence space."""
    d = 2 ** N
    Id = np.eye(d, dtype=complex)
    R = np.kron(Id, xn(N))            # R: rho -> rho F,  F = X^(x)N  (ONE-SIDED)
    D = swap_perm(N)                  # D: rho -> rho^T
    h_zx = ad_unitary(N, HAD)         # X<->Z involution
    t_yz = ad_unitary(N, T_YZ)        # Y<->Z involution
    t_xy = ad_unitary(N, T_XY)        # X<->Y involution
    return R, D, h_zx, t_yz, t_xy


def order_of(g, maxo=64):
    P = np.eye(g.shape[0], dtype=complex)
    for k in range(1, maxo + 1):
        P = P @ g
        if np.max(np.abs(P - np.eye(g.shape[0]))) < MATCH:
            return k
    return None


# ============================ Stage 0: conventions + D4 core (the gate) ============================
def stage0_gate(N=2):
    print(f"Stage 0 (gate): Pi_Z=R.D, D.Pi_Z.D=Pi_Y, |<R,D>|=8 on coherence space (N={N}):")
    R, D, *_ = ops(N)
    PiZ, PiY = pi_coh(N, "Z"), pi_coh(N, "Y")
    dev_fac = np.max(np.abs(PiZ - R @ D))
    dev_inv = np.max(np.abs(D @ PiZ @ D - PiY))
    d4 = group_closure([R, D], (2 ** N) ** 2)
    print(f"   |Pi_Z - R.D| = {dev_fac:.2e}   |D.Pi_Z.D - Pi_Y| = {dev_inv:.2e}   |<R,D>| = {len(d4)}")
    assert dev_fac < MATCH, "GATE: Pi_Z != R.D -- coherence-space Pi transform misconventioned."
    assert dev_inv < MATCH, "GATE: D.Pi_Z.D != Pi_Y -- dihedral inversion broken."
    assert len(d4) == 8, f"GATE: |<R,D>| = {len(d4)} != 8 (D4 core)."
    print("   [0] conventions consistent; D4 core = 8. OK")


# ============================ Stage 1: the letter-S3 EXISTS (order 6) ============================
def stage1_the_s3(N=2):
    print(f"\nStage 1: the letter-S3 from INVOLUTIVE transpositions (N={N}):")
    R, D, h_zx, t_yz, t_xy = ops(N)
    dim = (2 ** N) ** 2
    print(f"   element orders: ord(h_zx)={order_of(h_zx)} ord(t_yz)={order_of(t_yz)} ord(t_xy)={order_of(t_xy)}")
    n_s3 = len(group_closure([h_zx, t_yz], dim))
    n_three = len(group_closure([h_zx, t_yz, t_xy], dim))
    n_v4 = len(group_closure([D, h_zx], dim))
    print(f"   |<h_zx, t_yz>|        = {n_s3}   (S3: two involutions, product order 3)")
    print(f"   |<h_zx, t_yz, t_xy>|  = {n_three}  (all three involutive swaps -> the Clifford group; "
          f"the 3rd swap is NOT in the S3 of the first two, it differs by a Pauli sign)")
    print(f"   |<D, h_zx>|           = {n_v4}   (the honest dephase-swaps {{I,D,H,Q_zx}} = Klein-V4, abelian)")
    assert order_of(h_zx) == 2 and order_of(t_yz) == 2, "the letter transpositions must be involutions."
    assert n_s3 == 6, f"<h_zx,t_yz> = {n_s3}, expected 6 (the letter-S3)."
    assert n_three == 24, f"<h_zx,t_yz,t_xy> = {n_three}, expected 24 (Clifford group)."
    assert n_v4 == 4, f"<D,h_zx> = {n_v4}, expected 4 (Klein-V4)."
    print("   [1] the letter-S3 exists (order 6); all three swaps together give Clifford-24. OK")


# ============================ Stage 2: the closure is 96*2^N, NOT 48 ============================
def stage2_no_48(N=2):
    print(f"\nStage 2: the full closure is 96*2^N, NOT 48 (N={N}):")
    R, D, h_zx, t_yz, t_xy = ops(N)
    dim = (2 ** N) ** 2
    n_arc = len(group_closure([R, D, h_zx], dim))
    n_full = len(group_closure([R, D, h_zx, t_yz], dim))
    # tolerance-robustness: the count must not be a floating-point dedup artifact
    n_loose = len(group_closure([R, D, h_zx, t_yz], dim, tol=1e-3))
    print(f"   |<R,D,h_zx>|        = {n_arc}  (= 16*2^N; the arc's literal 'adjoin Q_zx')")
    print(f"   |<R,D,h_zx,t_yz>|   = {n_full}  (= 96*2^N; at tol=1e-3 also {n_loose} -> not an fp artifact)")
    assert n_arc == 16 * 2 ** N, f"<R,D,h_zx> = {n_arc}, expected 16*2^N = {16 * 2 ** N}."
    assert n_full == 96 * 2 ** N, f"<R,D,h_zx,t_yz> = {n_full}, expected 96*2^N = {96 * 2 ** N}."
    assert n_loose == n_full, f"tolerance-dependent count ({n_loose} vs {n_full}) -- would be an fp artifact."
    assert n_full != 48, "the order-48 premise would hold -- revisit if this ever fires."
    print(f"   [2] closure = {n_full} = 96*2^N, grows with N, robust to tol -> NO finite order-48. OK")


# ============================ Stage 3: WHY -- R spreads (the mechanism) ============================
def stage3_R_spreads(N=2):
    print(f"\nStage 3: the mechanism -- R = I(x)F is one-sided and SPREADS under the S3 (N={N}):")
    R, D, h_zx, *_ = ops(N)
    dim = (2 ** N) ** 2
    d = 2 ** N
    Id = np.eye(d, dtype=complex)
    Zn = Z1
    for _ in range(N - 1):
        Zn = np.kron(Zn, Z1)
    R_Z = np.kron(Id, Zn)                       # the one-sided multiplication rho -> rho Z^(x)N
    conj = h_zx @ R @ np.linalg.inv(h_zx)
    dev = np.max(np.abs(conj - R_Z))
    in_d4 = any(np.max(np.abs(conj - e)) < MATCH for e in group_closure([R, D], dim))
    print(f"   h_zx . R . h_zx^-1 = (rho -> rho Z^(x)N)?  dev = {dev:.2e}   in D4=<R,D>? {in_d4}")
    assert dev < MATCH, "h_zx . R . h_zx^-1 is not the one-sided Z^(x)N multiplication."
    assert not in_d4, "the spread image lands in D4 -- then the S3 WOULD normalize D4 (revisit)."
    print("   [3] R spreads: the S3 does NOT normalize D4 -> no semidirect order-48; the one-sided")
    print("       Pauli multiplications it generates are the 2^N growth (the O(2) completion's slice). OK")


# ============================ Stage 4: one S3, the diagonals vs the palindromizers ============================
def stage4_one_s3(N=2):
    print(f"\nStage 4: ONE S3, acting on the sign-blind diagonals and the signed palindromizers (N={N}):")
    R, D, h_zx, t_yz, t_xy = ops(N)
    dim = (2 ** N) ** 2
    s3 = group_closure([h_zx, t_yz], dim)
    Qs = [Q_diag(N, L) for L in ("X", "Y", "Z")]
    labels = ["X", "Y", "Z"]
    orbit_Q = orbit_of(Q_diag(N, "Z"), s3)
    orbit_Pi = orbit_of(pi_coh(N, "Z"), s3)
    # unsigned permutations of the diagonals induced by the S3:
    perms = set()
    for g in s3:
        ginv = np.linalg.inv(g)
        img = []
        for q in Qs:
            c = g @ q @ ginv
            hit = next((lab for lab, q2 in zip(labels, Qs)
                        if np.max(np.abs(c - q2)) < MATCH or np.max(np.abs(c + q2)) < MATCH), "?")
            img.append(hit)
        perms.add(tuple(img))
    print(f"   |S3| = {len(s3)}; orbit(Q_Z) = {len(orbit_Q)} (sign-blind diagonals), "
          f"orbit(Pi_Z) = {len(orbit_Pi)} (signed palindromizers)")
    print(f"   S3 permutes {{Q_X,Q_Y,Q_Z}} as {len(perms)} permutations (6 = full S3)")
    assert len(orbit_Q) == 3, f"Q_Z orbit = {len(orbit_Q)}, expected 3."
    assert len(perms) == 6, f"S3 permutes Q as {len(perms)}, expected the full S3 (6)."
    print("   [4] one S3: faithful on the diagonals (orbit 3, full S3); the palindromizers carry signs")
    print(f"       (orbit {len(orbit_Pi)}). There were never 'two S3's'. OK")


if __name__ == "__main__":
    for N in (2, 3):
        print(f"################################  N = {N}  ################################")
        stage0_gate(N)
        stage1_the_s3(N)
        stage2_no_48(N)
        stage3_R_spreads(N)
        stage4_one_s3(N)
        print()
    print("ALL STAGES PASS: no finite order-48 S3|xD4 on coherence space. The letter-S3 (order 6) exists")
    print("but does not normalize D4 (R = I(x)F spreads), so the closure is 96*2^N -- the discrete slice")
    print("of the O(2) completion that PROOF_PI_FACTORS_AS_R_TIMES_D.md sec.5's addendum already named.")
