using System;
using System.Linq;
using System.Numerics;
using MathNet.Numerics.LinearAlgebra;
using RCPsiSquared.Core.F89PathK;
using Xunit;
using Xunit.Abstractions;

namespace RCPsiSquared.Diagnostics.Tests.Foundation;

/// <summary>The FOLD LATTICE (PROOF_CODIM1_BY_ADDITIVITY §7, the block group of order 8): the joint-popcount
/// block lattice (p, q̃) ∈ [0,N]² carries a D₄ action generated by the transpose t: (p,q̃)↦(q̃,p), the bra fold
/// f_P: (p,q̃)↦(p,N−q̃) and the ket fold f_Q: (p,q̃)↦(N−p,q̃), and every leg is HOLOMORPHIC at Δ=0: composing
/// the four exact matrix-level ingredients [the transpose identity T·L₍p,q̃₎(q) = L₍q̃,p₎(−q)·T; the F89d bra/ket
/// antiunitary similarities L₍p,N−q̃₎(q̄) = −P·conj(L₍p,q̃₎(q))·Pᵀ − 2N·I and the ket mirror (both weights general,
/// F89CrossFoldSimilarityClaim); the pencil reality conj L(q) = L(−q̄) (A real, C entrywise imaginary); the
/// bipartite gauge 𝒟L(q)𝒟 = L(−q) (alternating-sign diagonal, DHD = −H)] cancels every conjugation and every
/// −q:
///
/// <code>
///   spec(q̃,p)(q)   =  spec(p,q̃)(q)                (t: the linear similarity 𝒟T)
///   spec(p,N−q̃)(q) = −spec(p,q̃)(q) − 2N           (f_P: L₍p,N−q̃₎(q) = −P𝒟·L₍p,q̃₎(q)·𝒟Pᵀ − 2N·I)
///   spec(N−p,q̃)(q) = −spec(p,q̃)(q) − 2N           (f_Q: the ket mirror)
/// </code>
///
/// all at the SAME q, matrix-level, hence Jordan-structure-preserving (the affine flip −(·)−2N maps
/// (L′−s(λ)) = −P𝒟(L−λ)𝒟Pᵀ, so generalized eigenspace dimensions transfer). The spectral cocycle is the
/// homomorphism χ: G → {id, s}, s(λ) = −λ−2N, χ = parity of fold legs; ker χ = {1, t, f_Pf_Q = Klein, tf_Pf_Q}.
/// CONSEQUENCES: (i) {λ_A, μ = −λ_A−2N} is s-invariant, so braid MEMBERSHIP and EXCLUSION are constant on
/// G-orbits: the broad-exclusion problem lives on a fundamental domain {p ≤ q̃, p+q̃ ≤ N}, ~⅛ of the lattice;
/// (ii) a block fixed by a fold leg (q̃ = N/2 or p = N/2, even N) carries an s-SYMMETRIC spectrum, the §7
/// even-N fine print as a corollary; (iii) the N=5 interior-four propagation (RemainderR4InteriorExclusionTests)
/// is the orbit statement for orbit((1,1)) = {(1,1),(4,4),(1,4),(4,1)}. At Δ ≠ 0 the bipartite gauge no longer
/// flips the (diagonal) Δ-frequency, so the fold legs connect q with −q instead: spec(p,N−q̃)(q,Δ) =
/// −spec(p,q̃)(−q,Δ) − 2N, still holomorphic (the last fact pins it).
///
/// <para>Run: <c>dotnet test "compute/RCPsiSquared.Diagnostics.Tests" --filter "Category=FOLDLATTICE"
/// --logger "console;verbosity=detailed"</c>.</para></summary>
public sealed class BlockLatticeFoldGroupTests
{
    private readonly ITestOutputHelper _out;
    public BlockLatticeFoldGroupTests(ITestOutputHelper o) => _out = o;

    private static readonly Complex[] ReferenceQs =
    {
        new(0.620878, 0),                                   // the N=5 real seed locus
        new(1.8141, 0.3666),                                // the R-even deep locus
        new(1.7701, 1.2189),                                // the R-odd escaper locus
        new(0.7, 0.3),                                      // a generic complex point
    };

    [Fact]
    [Trait("Category", "FOLDLATTICE")]
    public void QEvenness_BipartiteGauge_AllBlocks_N5()
    {
        var q = new Complex(0.7, 0.3);
        double worst = 0;
        foreach (var (p, w) in AllBlocks(5))
            worst = Math.Max(worst, MultisetDist(Spec(5, p, w, -q), Spec(5, p, w, q)));
        _out.WriteLine($"q-evenness spec(p,q̃)(−q) = spec(p,q̃)(q), all 36 blocks at N=5: worst {worst:E2}");
        Assert.True(worst < 1e-7, $"bipartite-gauge q-evenness must hold on every block; worst {worst:E2}");
    }

    [Fact]
    [Trait("Category", "FOLDLATTICE")]
    public void TransposeLeg_IsHolomorphic_AllBlocks_N5()
    {
        var q = new Complex(0.7, 0.3);
        double worst = 0;
        foreach (var (p, w) in AllBlocks(5))
            worst = Math.Max(worst, MultisetDist(Spec(5, w, p, q), Spec(5, p, w, q)));
        _out.WriteLine($"transpose leg spec(q̃,p)(q) = spec(p,q̃)(q), all blocks at N=5: worst {worst:E2}");
        Assert.True(worst < 1e-7, $"the holomorphic transpose leg must hold on every block; worst {worst:E2}");
    }

    [Fact]
    [Trait("Category", "FOLDLATTICE")]
    public void BraAndKetFolds_AreHolomorphic_AllBlocks_N5_AtTheLoci()
    {
        const int n = 5, twoN = 10;
        foreach (var q in ReferenceQs)
        {
            double worstP = 0, worstQ = 0;
            foreach (var (p, w) in AllBlocks(n))
            {
                var folded = Spec(n, p, w, q).Select(z => -z - twoN).ToArray();
                worstP = Math.Max(worstP, MultisetDist(Spec(n, p, n - w, q), folded));
                worstQ = Math.Max(worstQ, MultisetDist(Spec(n, n - p, w, q), folded));
            }
            _out.WriteLine($"q={q}: bra fold worst {worstP:E2}, ket fold worst {worstQ:E2} (all blocks)");
            Assert.True(worstP < 1e-7, $"the holomorphic bra fold must hold on every block at q={q}; worst {worstP:E2}");
            Assert.True(worstQ < 1e-7, $"the holomorphic ket fold must hold on every block at q={q}; worst {worstQ:E2}");
        }
    }

    [Fact]
    [Trait("Category", "FOLDLATTICE")]
    public void SelfFoldedBlocks_CarrySSymmetricSpectra_N6()
    {
        // Even N: q̃ = N/2 is fold-fixed under f_P, so spec(p, N/2) must equal −spec(p, N/2) − 2N as a
        // multiset: the §7 fine print ("the four members around half filling carry BOTH λ and −λ̄−2N")
        // as a corollary of the stabilizer cocycle χ(f_P) = s.
        const int n = 6, twoN = 12;
        var q = new Complex(0.7, 0.3);
        for (int p = 0; p <= n; p++)
        {
            var s = Spec(n, p, n / 2, q);
            double d = MultisetDist(s, s.Select(z => -z - twoN).ToArray());
            _out.WriteLine($"(p={p}, q̃=3) at N=6: dim {s.Length}, s-symmetry residual {d:E2}");
            Assert.True(d < 1e-7, $"the fold-fixed block (p={p}, 3) must carry an s-symmetric spectrum; got {d:E2}");
        }
    }

    [Fact]
    [Trait("Category", "FOLDLATTICE")]
    public void FundamentalDomain_TransfersEveryBlock_N5()
    {
        // The quotient statement: every block's spectrum is the χ-transfer of its fundamental-domain
        // representative (lexicographic minimum over the 8 images), so the lattice reduces to ~1/8.
        const int n = 5, twoN = 10;
        var q = new Complex(1.8141, 0.3666);
        int orbits = 0;
        double worst = 0;
        var seen = new bool[n + 1, n + 1];
        foreach (var (p, w) in AllBlocks(n))
        {
            if (seen[p, w]) continue;
            orbits++;
            var repSpec = Spec(n, p, w, q);
            foreach (var (gp, gw, foldParity) in OrbitImages(n, p, w))
            {
                seen[gp, gw] = true;
                var expected = foldParity == 0 ? repSpec : repSpec.Select(z => -z - twoN).ToArray();
                worst = Math.Max(worst, MultisetDist(Spec(n, gp, gw, q), expected));
            }
        }
        _out.WriteLine($"N=5 lattice: 36 blocks fall into {orbits} G-orbits; worst χ-transfer residual {worst:E2}");
        Assert.True(worst < 1e-7, $"every block must be the χ-transfer of its orbit representative; worst {worst:E2}");
        Assert.True(orbits <= 8, $"the 36-block lattice must compress to at most 8 orbits; got {orbits}");
    }

    [Fact]
    [Trait("Category", "FOLDLATTICE")]
    public void AtNonzeroDelta_TheFoldConnects_QWithMinusQ()
    {
        // Δ ≠ 0: the Δ-frequency is diagonal, so the BIPARTITE GAUGE no longer supplies q → −q; the fold
        // legs remain holomorphic but connect q with −q (P∘reality, no evenness needed). q-evenness then
        // survives EXACTLY on the two fixed lines of the residual group action: p = q̃ (the transpose t is a
        // self-map) and p + q̃ = N (t∘Klein is a self-map: Klein (p,N−p)→(N−p,p), t back), both valid at every
        // Δ because T and the Klein full flip are Δ-robust (Hᵀ = H incl. ZZ; n_diff and zz invariant under the
        // full complement). Off those lines evenness genuinely breaks, and with it the same-q fold: the
        // negative control that separates the Δ=0 lemma (bipartite gauge, everything same-q) from Δ ≠ 0.
        const int n = 5, twoN = 10;
        const double delta = 0.3;
        var q = new Complex(0.7, 0.3);
        foreach (var (p, w) in new[] { (1, 2), (2, 2), (1, 1), (2, 3) })
        {
            var target = SpecD(n, p, n - w, q, delta);
            double dMinus = MultisetDist(target, SpecD(n, p, w, -q, delta).Select(z => -z - twoN).ToArray());
            double dSame = MultisetDist(target, SpecD(n, p, w, q, delta).Select(z => -z - twoN).ToArray());
            double dEven = MultisetDist(SpecD(n, p, w, -q, delta), SpecD(n, p, w, q, delta));
            _out.WriteLine($"Δ={delta}, source ({p},{w}): −q fold {dMinus:E2}, same-q fold {dSame:E2}, q-evenness {dEven:E2}");
            Assert.True(dMinus < 1e-7, $"at Δ≠0 the bra fold against −q must hold for ({p},{w}); got {dMinus:E2}");
            bool onFixedLine = p == w || p + w == n;
            if (onFixedLine)
                Assert.True(dEven < 1e-7, $"({p},{w}) sits on a fixed line (p=q̃ or p+q̃=N): q-even at every Δ; got {dEven:E2}");
            else
                Assert.True(dEven > 1e-2, $"({p},{w}) off the fixed lines: q-evenness must break at Δ≠0 (negative control); got {dEven:E2}");
        }
    }

    // ---- the D₄ orbit machinery (index maps + fold parity) ----

    private static (int P, int W)[] AllBlocks(int n)
        => Enumerable.Range(0, n + 1).SelectMany(p => Enumerable.Range(0, n + 1).Select(w => (p, w))).ToArray();

    /// <summary>The 8 images of (p, w) under G = ⟨t, f_P, f_Q⟩ with the fold parity (#fold legs mod 2).</summary>
    private static (int P, int W, int FoldParity)[] OrbitImages(int n, int p, int w) => new[]
    {
        (p, w, 0), (w, p, 0), (n - p, n - w, 0), (n - w, n - p, 0),                 // ker χ: 1, t, Klein, t·Klein
        (p, n - w, 1), (n - p, w, 1), (n - w, p, 1), (w, n - p, 1),                 // the fold coset
    };

    private static Complex[] Spec(int n, int wk, int wb, Complex q) =>
        Matrix<Complex>.Build.DenseOfArray(WeightCoherenceBlock.Build(n, wk, wb, q)).Evd().EigenValues.ToArray();

    private static Complex[] SpecD(int n, int wk, int wb, Complex q, double delta) =>
        Matrix<Complex>.Build.DenseOfArray(WeightCoherenceBlock.Build(n, wk, wb, q, delta)).Evd().EigenValues.ToArray();

    /// <summary>Greedy multiset distance (the sorted-zip artifact guard: never sort-then-zip fold images).</summary>
    private static double MultisetDist(Complex[] a, Complex[] b)
    {
        if (a.Length != b.Length) return double.NaN;
        var used = new bool[b.Length];
        double worst = 0;
        foreach (var z in a)
        {
            int best = -1; double bd = double.PositiveInfinity;
            for (int j = 0; j < b.Length; j++)
                if (!used[j]) { double dd = (z - b[j]).Magnitude; if (dd < bd) { bd = dd; best = j; } }
            used[best] = true; worst = Math.Max(worst, bd);
        }
        return worst;
    }
}
